import { build, context } from 'esbuild';

const watch = process.argv.includes('--watch');

const options = {
    entryPoints: ['src/index.js'],
    outfile: 'index.js',
    bundle: true,
    format: 'esm',
    target: ['es2020'],
    platform: 'browser',
    charset: 'utf8',
    sourcemap: false,
    logLevel: 'info',
    banner: {
        js: '/* Generated by esbuild from src/. Edit files in src/ and run: npm run build */',
    },
};

if (watch) {
    const ctx = await context(options);
    await ctx.watch();
    console.log('[token-monitor] watching for changes...');
} else {
    await build(options);
}
