/* Generated by esbuild from src/. Edit files in src/ and run: npm run build */

// src/tokens.js
var QUIET_TYPES = /* @__PURE__ */ new Set(["quiet"]);
var TOKEN_CACHE_MAX = 400;
var ESTIMATE_CHARS_PER_TOKEN = 1.5;
var tokenCache = /* @__PURE__ */ new Map();
var pendingInputTokens = null;
function ctx() {
  return globalThis.SillyTavern?.getContext();
}
function hashString(text) {
  let hash = 5381;
  for (let i = 0; i < text.length; i++) {
    hash = (hash << 5) + hash + text.charCodeAt(i) | 0;
  }
  return (hash >>> 0).toString(36);
}
function initTokenTracking() {
  globalThis.tokenMonitorInterceptor = function(_chat, contextSize, _abort, type) {
    if (QUIET_TYPES.has(type)) {
      return;
    }
    const value = Number(contextSize);
    if (Number.isFinite(value) && value > 0) {
      pendingInputTokens = value;
    }
  };
}
async function countTextAsync(text) {
  const context = ctx();
  if (!context || typeof context.getTokenCountAsync !== "function") {
    return null;
  }
  try {
    const count = await context.getTokenCountAsync(text ?? "");
    return Number.isFinite(count) ? count : null;
  } catch (error) {
    console.error("[TokenMonitor] token count failed:", error);
    return null;
  }
}
async function countTokensCached(text) {
  const value = text ?? "";
  const key = `${hashString(value)}:${value.length}`;
  if (tokenCache.has(key)) {
    const cached = tokenCache.get(key);
    tokenCache.delete(key);
    tokenCache.set(key, cached);
    return cached;
  }
  const count = await countTextAsync(value);
  if (count !== null) {
    tokenCache.set(key, count);
    if (tokenCache.size > TOKEN_CACHE_MAX) {
      const oldest = tokenCache.keys().next().value;
      tokenCache.delete(oldest);
    }
  }
  return count;
}
async function countMsgTokens(messages) {
  let total = 0;
  for (const message of messages ?? []) {
    const raw = typeof message === "string" ? message : message?.content ?? "";
    const text = typeof raw === "string" ? raw : JSON.stringify(raw ?? "");
    const count = await countTokensCached(text);
    total += count !== null ? count : Math.ceil(text.length / ESTIMATE_CHARS_PER_TOKEN);
  }
  return total;
}
function consumePendingInput() {
  const value = pendingInputTokens;
  pendingInputTokens = null;
  return value;
}
function clearPendingInput() {
  pendingInputTokens = null;
}

// src/store.js
var DATA_KEY = "token_monitor";
var UNATTRIBUTED_KEY = "token_monitor_unattributed";
var SCHEMA_VERSION = 2;
var SAVE_DEBOUNCE_MS = 1500;
var AUX_CATEGORIES = ["plot", "fill", "other"];
var PLOT_MATCH_RETRIES = 40;
var PLOT_MATCH_INTERVAL_MS = 1e3;
var FILL_TEXT_MIN_LENGTH = 60;
var TEXT_MATCH_MIN_LENGTH = 20;
var saveTimer = null;
function ctx2() {
  return globalThis.SillyTavern?.getContext();
}
function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function toNumber(value) {
  const num = Number(value);
  return Number.isFinite(num) ? num : 0;
}
function isTrackable(message) {
  return Boolean(message) && typeof message === "object" && message.is_system !== true && typeof message.mes === "string";
}
function emptyCategory() {
  return { calls: 0, input: 0, output: 0, byModel: {} };
}
function emptyAux() {
  return { plot: emptyCategory(), fill: emptyCategory(), other: emptyCategory() };
}
function normalizeByModel(byModel) {
  const result = {};
  if (!byModel || typeof byModel !== "object") {
    return result;
  }
  for (const [model, value] of Object.entries(byModel)) {
    result[model] = {
      calls: toNumber(value?.calls),
      input: toNumber(value?.input),
      output: toNumber(value?.output)
    };
  }
  return result;
}
function normalizeAux(aux) {
  const result = emptyAux();
  if (!aux || typeof aux !== "object") {
    return result;
  }
  for (const category of AUX_CATEGORIES) {
    const source = aux[category];
    if (!source || typeof source !== "object") {
      continue;
    }
    result[category] = {
      calls: toNumber(source.calls),
      input: toNumber(source.input),
      output: toNumber(source.output),
      byModel: normalizeByModel(source.byModel)
    };
  }
  return result;
}
function addToCategory(category, { model, input, output }) {
  category.calls += 1;
  category.input += toNumber(input);
  category.output += toNumber(output);
  const key = model || "";
  if (!key) {
    return;
  }
  const entry = category.byModel[key] ?? { calls: 0, input: 0, output: 0 };
  entry.calls += 1;
  entry.input += toNumber(input);
  entry.output += toNumber(output);
  category.byModel[key] = entry;
}
function mergeCategory(target, source) {
  target.calls += toNumber(source.calls);
  target.input += toNumber(source.input);
  target.output += toNumber(source.output);
  for (const [model, value] of Object.entries(source.byModel ?? {})) {
    const entry = target.byModel[model] ?? { calls: 0, input: 0, output: 0 };
    entry.calls += toNumber(value.calls);
    entry.input += toNumber(value.input);
    entry.output += toNumber(value.output);
    target.byModel[model] = entry;
  }
}
function aggregateAuxByModel(aux) {
  const result = {};
  for (const category of AUX_CATEGORIES) {
    for (const [model, value] of Object.entries(aux[category].byModel)) {
      const entry = result[model] ?? { calls: 0, input: 0, output: 0 };
      entry.calls += toNumber(value.calls);
      entry.input += toNumber(value.input);
      entry.output += toNumber(value.output);
      result[model] = entry;
    }
  }
  return result;
}
function buildData({ input, output, aux, ts }) {
  return {
    v: SCHEMA_VERSION,
    input: input ?? null,
    output: output ?? null,
    total: (input ?? 0) + (output ?? 0),
    aux: normalizeAux(aux),
    ts: ts ?? Date.now()
  };
}
function getMessageTokens(message) {
  return message?.extra?.[DATA_KEY] ?? null;
}
function attach(message, data) {
  if (!message.extra || typeof message.extra !== "object") {
    message.extra = {};
  }
  message.extra[DATA_KEY] = data;
}
async function updateMessageTokens(message, { usePendingInput = false } = {}) {
  if (!isTrackable(message)) {
    return null;
  }
  const existing = getMessageTokens(message) ?? {};
  const own = await countTextAsync(message.mes);
  const isUser = message.is_user === true;
  const input = isUser ? own : usePendingInput ? consumePendingInput() ?? existing.input ?? null : existing.input ?? null;
  const output = isUser ? 0 : own;
  const data = buildData({ input, output, aux: existing.aux, ts: existing.ts });
  attach(message, data);
  scheduleSave();
  return data;
}
async function recomputeChat() {
  const context = ctx2();
  const chat = context?.chat ?? [];
  for (const message of chat) {
    if (!isTrackable(message)) {
      continue;
    }
    const existing = getMessageTokens(message) ?? {};
    const own = await countTextAsync(message.mes);
    const isUser = message.is_user === true;
    const input = isUser ? own : existing.input ?? null;
    const output = isUser ? 0 : own;
    attach(message, buildData({ input, output, aux: existing.aux, ts: existing.ts }));
  }
  await flushSave();
}
function textMatches(a, b) {
  if (!a || !b) {
    return false;
  }
  if (a === b) {
    return true;
  }
  if (a.length >= TEXT_MATCH_MIN_LENGTH && b.includes(a)) {
    return true;
  }
  if (b.length >= TEXT_MATCH_MIN_LENGTH && a.includes(b)) {
    return true;
  }
  return false;
}
function findPlotMessage(responseText) {
  if (!responseText) {
    return null;
  }
  const chat = ctx2()?.chat ?? [];
  for (let i = chat.length - 1; i >= 0; i--) {
    const message = chat[i];
    if (!message || message.is_system === true) {
      continue;
    }
    if (textMatches(message.qrf_plot, responseText)) {
      return message;
    }
    const tasks = message.qrf_plot_tasks;
    if (tasks && typeof tasks === "object") {
      for (const value of Object.values(tasks)) {
        if (typeof value === "string" && textMatches(value, responseText)) {
          return message;
        }
      }
    }
  }
  return null;
}
function hasPlotMatch(responseText) {
  return Boolean(findPlotMessage(responseText));
}
function findNearestUserMessage(chatLenAt) {
  const chat = ctx2()?.chat ?? [];
  const limit = Number.isInteger(chatLenAt) && chatLenAt > 0 && chatLenAt <= chat.length ? chatLenAt : chat.length;
  for (let i = limit - 1; i >= 0; i--) {
    if (chat[i]?.is_user === true) {
      return chat[i];
    }
  }
  return null;
}
function findDeepestMatchingAiFloor(requestTexts) {
  const chat = ctx2()?.chat ?? [];
  for (let i = chat.length - 1; i >= 0; i--) {
    const message = chat[i];
    if (!message || message.is_system === true) {
      continue;
    }
    const mes = typeof message.mes === "string" ? message.mes : "";
    if (mes.length < FILL_TEXT_MIN_LENGTH) {
      continue;
    }
    if (requestTexts.some((text) => text.includes(mes) || mes.includes(text))) {
      if (message.is_user !== true) {
        return message;
      }
    }
  }
  return null;
}
function findLatestAiFloor() {
  const chat = ctx2()?.chat ?? [];
  for (let i = chat.length - 1; i >= 0; i--) {
    const message = chat[i];
    if (message && message.is_system !== true && message.is_user !== true) {
      return message;
    }
  }
  return null;
}
function addAuxToMessage(message, category, record) {
  if (!isTrackable(message)) {
    addUnattributed(category, record);
    return;
  }
  const existing = getMessageTokens(message) ?? {};
  const data = buildData({
    input: existing.input ?? null,
    output: existing.output ?? null,
    aux: existing.aux,
    ts: existing.ts
  });
  addToCategory(data.aux[category], record);
  attach(message, data);
}
function addUnattributed(category, record) {
  const context = ctx2();
  if (!context?.chatMetadata) {
    return;
  }
  const bucket = normalizeAux(context.chatMetadata[UNATTRIBUTED_KEY]);
  addToCategory(bucket[category], record);
  context.chatMetadata[UNATTRIBUTED_KEY] = bucket;
  if (typeof context.saveMetadataDebounced === "function") {
    context.saveMetadataDebounced();
  }
}
async function recordPlotUsage(record) {
  let target = findPlotMessage(record.responseText);
  if (!target && record.responseText) {
    for (let attempt = 0; attempt < PLOT_MATCH_RETRIES && !target; attempt++) {
      await delay(PLOT_MATCH_INTERVAL_MS);
      target = findPlotMessage(record.responseText);
    }
  }
  if (!target) {
    target = findNearestUserMessage(record.chatLenAt);
  }
  if (!target) {
    addUnattributed("plot", record);
    return;
  }
  addAuxToMessage(target, "plot", record);
  scheduleSave();
}
function recordFillUsage(record) {
  const requestTexts = (record.requestTexts ?? []).map((item) => item?.content).filter((text) => typeof text === "string" && text.length > 0);
  const target = findDeepestMatchingAiFloor(requestTexts) ?? findLatestAiFloor();
  if (!target) {
    addUnattributed("fill", record);
    return;
  }
  addAuxToMessage(target, "fill", record);
  scheduleSave();
}
async function recordAuxUsage(record) {
  if (!record || !AUX_CATEGORIES.includes(record.category)) {
    return;
  }
  if (record.category === "plot") {
    await recordPlotUsage(record);
    return;
  }
  if (record.category === "fill") {
    recordFillUsage(record);
    return;
  }
  addUnattributed(record.category, record);
}
function computeChatSummary() {
  const context = ctx2();
  const chat = context?.chat ?? [];
  let totalInput = 0;
  let totalOutput = 0;
  let ownTotal = 0;
  let counted = 0;
  let messageCount = 0;
  let lastInput = null;
  const aux = emptyAux();
  for (const message of chat) {
    if (!message || message.is_system === true) {
      continue;
    }
    messageCount += 1;
    const data = getMessageTokens(message);
    if (!data) {
      continue;
    }
    const input = Number(data.input);
    const output = Number(data.output);
    const hasInput = Number.isFinite(input);
    const hasOutput = Number.isFinite(output);
    totalInput += hasInput ? input : 0;
    totalOutput += hasOutput ? output : 0;
    ownTotal += message.is_user === true ? hasInput ? input : 0 : hasOutput ? output : 0;
    counted += 1;
    if (message.is_user !== true && hasInput) {
      lastInput = input;
    }
    if (data.aux) {
      const normalized = normalizeAux(data.aux);
      for (const category of AUX_CATEGORIES) {
        mergeCategory(aux[category], normalized[category]);
      }
    }
  }
  const unattributed = normalizeAux(context?.chatMetadata?.[UNATTRIBUTED_KEY]);
  for (const category of AUX_CATEGORIES) {
    mergeCategory(aux[category], unattributed[category]);
  }
  return {
    totalInput,
    totalOutput,
    total: totalInput + totalOutput,
    ownTotal,
    counted,
    messageCount,
    lastInput,
    aux,
    auxByModel: aggregateAuxByModel(aux)
  };
}
function updateChatSummary() {
  const context = ctx2();
  if (!context?.chatMetadata) {
    return;
  }
  const summary = computeChatSummary();
  context.chatMetadata[DATA_KEY] = {
    v: SCHEMA_VERSION,
    totalInput: summary.totalInput,
    totalOutput: summary.totalOutput,
    aux: summary.aux,
    updatedAt: Date.now()
  };
  if (typeof context.saveMetadataDebounced === "function") {
    context.saveMetadataDebounced();
  }
}
function scheduleSave() {
  if (saveTimer) {
    clearTimeout(saveTimer);
  }
  saveTimer = setTimeout(() => {
    saveTimer = null;
    void flushSave();
  }, SAVE_DEBOUNCE_MS);
}
async function flushSave() {
  const context = ctx2();
  updateChatSummary();
  if (context && typeof context.saveChat === "function") {
    try {
      await context.saveChat();
    } catch (error) {
      console.error("[TokenMonitor] save chat failed:", error);
    }
  }
}
function clearChatTokenData() {
  const context = ctx2();
  const chat = context?.chat ?? [];
  for (const message of chat) {
    if (message?.extra && Object.hasOwn(message.extra, DATA_KEY)) {
      delete message.extra[DATA_KEY];
    }
  }
  if (context?.chatMetadata) {
    delete context.chatMetadata[DATA_KEY];
    delete context.chatMetadata[UNATTRIBUTED_KEY];
  }
  void flushSave();
}
function clearAllTokenData() {
  clearChatTokenData();
}

// src/interceptor.js
var GENERATE_PATH = "/api/backends/chat-completions/generate";
var FILL_WINDOW_TTL_MS = 12e4;
var PLOT_WINDOW_TTL_MS = 18e4;
var AUTOCARD_RETRY_INTERVAL_MS = 5e3;
var AUTOCARD_RETRY_MAX = 60;
var classification = { mode: "auto", plotMarkers: [], fillMarkers: [] };
var observer = { instance: null };
var patchedWindows = /* @__PURE__ */ new Map();
var plotWindowOpen = false;
var plotWindowTimer = null;
var fillWindowOpen = false;
var fillWindowTimer = null;
var stHandlers = null;
var autoCardCallback = null;
var autoCardRetryTimer = null;
var autoCardRetryCount = 0;
var seq = 0;
function ctx3() {
  return globalThis.SillyTavern?.getContext();
}
function getChatLength() {
  const chat = ctx3()?.chat;
  return Array.isArray(chat) ? chat.length : 0;
}
function openFillWindow() {
  fillWindowOpen = true;
  if (fillWindowTimer) {
    clearTimeout(fillWindowTimer);
  }
  fillWindowTimer = setTimeout(() => {
    fillWindowOpen = false;
    fillWindowTimer = null;
  }, FILL_WINDOW_TTL_MS);
}
function openPlotWindow() {
  plotWindowOpen = true;
  if (plotWindowTimer) {
    clearTimeout(plotWindowTimer);
  }
  plotWindowTimer = setTimeout(() => {
    plotWindowOpen = false;
    plotWindowTimer = null;
  }, PLOT_WINDOW_TTL_MS);
}
function closePlotWindow() {
  plotWindowOpen = false;
  if (plotWindowTimer) {
    clearTimeout(plotWindowTimer);
    plotWindowTimer = null;
  }
}
function installClassifierEvents() {
  const context = ctx3();
  const eventSource = context?.eventSource;
  const eventTypes = context?.eventTypes;
  if (!eventSource || !eventTypes || stHandlers) {
    return;
  }
  stHandlers = {
    plotOpen: () => openPlotWindow(),
    plotClose: () => closePlotWindow(),
    fillOpen: () => openFillWindow(),
    chatChanged: () => scheduleAutoCardRetry(true)
  };
  eventSource.on(eventTypes.GENERATION_AFTER_COMMANDS, stHandlers.plotOpen);
  eventSource.on(eventTypes.GENERATION_STARTED, stHandlers.plotClose);
  eventSource.on(eventTypes.GENERATION_ENDED, stHandlers.fillOpen);
  if (eventTypes.CHAT_CHANGED) {
    eventSource.on(eventTypes.CHAT_CHANGED, stHandlers.chatChanged);
  }
}
function uninstallClassifierEvents() {
  const context = ctx3();
  const eventSource = context?.eventSource;
  const eventTypes = context?.eventTypes;
  if (eventSource && eventTypes && stHandlers) {
    eventSource.removeListener?.(eventTypes.GENERATION_AFTER_COMMANDS, stHandlers.plotOpen);
    eventSource.removeListener?.(eventTypes.GENERATION_STARTED, stHandlers.plotClose);
    eventSource.removeListener?.(eventTypes.GENERATION_ENDED, stHandlers.fillOpen);
    if (eventTypes.CHAT_CHANGED) {
      eventSource.removeListener?.(eventTypes.CHAT_CHANGED, stHandlers.chatChanged);
    }
  }
  stHandlers = null;
}
function getAutoCardApi() {
  return globalThis.AutoCardUpdaterAPI ?? globalThis.topLevelWindow?.AutoCardUpdaterAPI ?? null;
}
function registerAutoCardHooks() {
  const api = getAutoCardApi();
  if (!api || typeof api.registerTableFillStartCallback !== "function") {
    return false;
  }
  if (autoCardCallback) {
    return true;
  }
  autoCardCallback = () => openFillWindow();
  try {
    api.registerTableFillStartCallback(autoCardCallback);
    return true;
  } catch (error) {
    console.warn("[TokenMonitor] registerTableFillStartCallback failed:", error);
    autoCardCallback = null;
    return false;
  }
}
function unregisterAutoCardHooks() {
  const api = getAutoCardApi();
  if (api && autoCardCallback && typeof api.unregisterTableFillStartCallback === "function") {
    try {
      api.unregisterTableFillStartCallback(autoCardCallback);
    } catch (error) {
      console.warn("[TokenMonitor] unregisterTableFillStartCallback failed:", error);
    }
  }
  autoCardCallback = null;
}
function stopAutoCardRetry() {
  if (autoCardRetryTimer) {
    clearInterval(autoCardRetryTimer);
    autoCardRetryTimer = null;
  }
}
function scheduleAutoCardRetry(reset = false) {
  if (reset) {
    autoCardRetryCount = 0;
  }
  if (registerAutoCardHooks()) {
    stopAutoCardRetry();
    return;
  }
  if (autoCardRetryTimer) {
    return;
  }
  autoCardRetryTimer = setInterval(() => {
    autoCardRetryCount += 1;
    if (registerAutoCardHooks() || autoCardRetryCount >= AUTOCARD_RETRY_MAX) {
      stopAutoCardRetry();
    }
  }, AUTOCARD_RETRY_INTERVAL_MS);
}
function collectSameOriginWindows(rootDocument, result) {
  let iframes;
  try {
    iframes = rootDocument.querySelectorAll("iframe");
  } catch {
    return result;
  }
  iframes.forEach((iframe) => {
    if (!iframe.__tokenMonitorLoadBound) {
      iframe.__tokenMonitorLoadBound = true;
      iframe.addEventListener("load", () => scanIframes());
    }
    let win = null;
    try {
      win = iframe.contentWindow;
    } catch {
      win = null;
    }
    if (!win) {
      return;
    }
    try {
      if (!win.document) {
        return;
      }
    } catch {
      return;
    }
    if (!result.includes(win)) {
      result.push(win);
    }
    try {
      collectSameOriginWindows(win.document, result);
    } catch {
    }
  });
  return result;
}
function patchWindow(win) {
  if (!win || win.__tokenMonitorAuxHooked) {
    return;
  }
  if (typeof win.fetch !== "function") {
    return;
  }
  const original = win.fetch.bind(win);
  patchedWindows.set(win, win.fetch);
  win.fetch = createWrappedFetch(original);
  win.__tokenMonitorAuxHooked = true;
}
function pruneClosedWindows() {
  for (const win of [...patchedWindows.keys()]) {
    try {
      if (win.closed) {
        patchedWindows.delete(win);
      }
    } catch {
      patchedWindows.delete(win);
    }
  }
}
function scanIframes() {
  if (typeof document === "undefined") {
    return;
  }
  pruneClosedWindows();
  for (const win of collectSameOriginWindows(document, [])) {
    patchWindow(win);
  }
}
function isGenerateUrl(url) {
  if (typeof url !== "string" || !url) {
    return false;
  }
  const path = url.split("?")[0].split("#")[0];
  return path.endsWith(GENERATE_PATH);
}
function contentToText(content) {
  if (typeof content === "string") {
    return content;
  }
  if (Array.isArray(content)) {
    return content.map((part) => typeof part?.text === "string" ? part.text : "").join("");
  }
  if (content == null) {
    return "";
  }
  return String(content);
}
function extractRequestTexts(body) {
  return (body.messages ?? []).map((message) => ({
    role: message?.role,
    content: contentToText(message?.content)
  }));
}
function matchMarkers(text, markers) {
  return markers.some((marker) => marker && text.includes(marker));
}
function classifyAtRequest(body) {
  const requestText = extractRequestTexts(body).map((item) => item.content).join("\n");
  if (matchMarkers(requestText, classification.plotMarkers)) {
    return "plot";
  }
  if (matchMarkers(requestText, classification.fillMarkers)) {
    return "fill";
  }
  if (classification.mode === "markers-only") {
    return null;
  }
  if (fillWindowOpen) {
    return "fill";
  }
  if (plotWindowOpen) {
    return "plot";
  }
  return null;
}
function resolveCategory(record) {
  if (record.categoryHint) {
    return record.categoryHint;
  }
  if (hasPlotMatch(record.responseText)) {
    return "plot";
  }
  return "other";
}
async function readSse(response) {
  let text = "";
  let usage = null;
  const reader = response.body?.getReader?.();
  if (!reader) {
    return { text, usage };
  }
  const decoder = new TextDecoder();
  let buffer = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("data:")) {
        continue;
      }
      const payload = trimmed.slice(5).trim();
      if (!payload || payload === "[DONE]") {
        continue;
      }
      try {
        const chunk = JSON.parse(payload);
        const delta = chunk?.choices?.[0]?.delta?.content;
        if (typeof delta === "string") {
          text += delta;
        }
        if (chunk?.usage) {
          usage = chunk.usage;
        }
      } catch {
      }
    }
  }
  return { text, usage };
}
function collectResponse(response, record) {
  const clone = response.clone();
  const contentType = clone.headers?.get?.("content-type") ?? "";
  if (contentType.includes("text/event-stream")) {
    void readSse(clone).then(({ text, usage }) => {
      record.responseText = text;
      record.usage = usage;
      ingest(record);
    }).catch(() => ingest(record));
    return;
  }
  void clone.json().then((payload) => {
    record.usage = payload?.usage ?? null;
    record.responseText = payload?.choices?.[0]?.message?.content ?? "";
    ingest(record);
  }).catch(() => ingest(record));
}
function createWrappedFetch(original) {
  return async function tokenMonitorFetch(input, init) {
    const url = typeof input === "string" ? input : input?.url ?? "";
    let body = null;
    try {
      const raw = init?.body ?? (input && typeof input === "object" ? input.body : null);
      if (typeof raw === "string") {
        body = JSON.parse(raw);
      }
    } catch {
      body = null;
    }
    const interceptable = isGenerateUrl(url) && body && Array.isArray(body.messages) && body.messages.length > 0;
    const record = interceptable ? {
      seq: ++seq,
      ts: Date.now(),
      model: body.model || "",
      requestTexts: extractRequestTexts(body),
      stream: Boolean(body.stream),
      responseText: "",
      usage: null,
      categoryHint: classifyAtRequest(body),
      chatLenAt: getChatLength()
    } : null;
    const response = await original(input, init);
    if (record) {
      try {
        collectResponse(response, record);
      } catch (error) {
        console.error("[TokenMonitor] aux capture failed:", error);
      }
    }
    return response;
  };
}
function ingest(record) {
  if (typeof globalThis.__tokenMonitorIngest === "function") {
    void globalThis.__tokenMonitorIngest(record);
  }
}
async function handleIngest(record) {
  try {
    const usage = record.usage ?? null;
    const usageInput = Number(usage?.prompt_tokens);
    const usageOutput = Number(usage?.completion_tokens);
    const input = Number.isFinite(usageInput) ? usageInput : await countMsgTokens(record.requestTexts);
    const output = Number.isFinite(usageOutput) ? usageOutput : await countTokensCached(record.responseText ?? "");
    await recordAuxUsage({
      category: resolveCategory(record),
      model: record.model,
      input: input ?? 0,
      output: output ?? 0,
      chatLenAt: record.chatLenAt,
      responseText: record.responseText,
      requestTexts: record.requestTexts,
      ts: record.ts
    });
  } catch (error) {
    console.error("[TokenMonitor] aux ingest failed:", error);
  }
}
function installAuxFetchInterceptor() {
  globalThis.__tokenMonitorIngest = handleIngest;
  installClassifierEvents();
  scheduleAutoCardRetry();
  scanIframes();
  if (!observer.instance && typeof MutationObserver === "function" && typeof document !== "undefined") {
    observer.instance = new MutationObserver(() => scanIframes());
    observer.instance.observe(document.documentElement, { childList: true, subtree: true });
  }
}
function uninstallAuxFetchInterceptor() {
  for (const [win, original] of patchedWindows) {
    try {
      win.fetch = original;
      delete win.__tokenMonitorAuxHooked;
    } catch {
    }
  }
  patchedWindows.clear();
  observer.instance?.disconnect();
  observer.instance = null;
  stopAutoCardRetry();
  unregisterAutoCardHooks();
  uninstallClassifierEvents();
  if (globalThis.__tokenMonitorIngest === handleIngest) {
    delete globalThis.__tokenMonitorIngest;
  }
}
function setMarkerConfig({ mode, plotMarkers, fillMarkers } = {}) {
  if (typeof mode === "string") {
    classification.mode = mode;
  }
  if (Array.isArray(plotMarkers)) {
    classification.plotMarkers = plotMarkers.map(String).filter(Boolean);
  }
  if (Array.isArray(fillMarkers)) {
    classification.fillMarkers = fillMarkers.map(String).filter(Boolean);
  }
}
function rescanAuxFrames() {
  scanIframes();
  scheduleAutoCardRetry(true);
}

// src/pricing.js
var DB_NAME = "token_monitor_pricing";
var STORE_NAME = "pricing";
var DB_VERSION = 1;
var CACHE_KEY = "catalogue";
var PRICE_URLS = [
  "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json",
  "https://gcore.jsdelivr.net/gh/BerriAI/litellm@main/model_prices_and_context_window.json",
  "https://cdn.jsdelivr.net/gh/BerriAI/litellm@main/model_prices_and_context_window.json",
  "https://fastly.jsdelivr.net/gh/BerriAI/litellm@main/model_prices_and_context_window.json"
];
var MIN_FUZZY_LENGTH = 6;
var MIN_VALID_ENTRIES = 3;
var SEARCH_RESULT_LIMIT = 40;
var byKey = /* @__PURE__ */ new Map();
var byTail = /* @__PURE__ */ new Map();
var meta = { count: 0, updatedAt: null };
function openDb() {
  return new Promise((resolve, reject) => {
    if (typeof indexedDB === "undefined") {
      reject(new Error("IndexedDB unavailable"));
      return;
    }
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME);
      }
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}
async function idbGet(key) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readonly");
    const request = tx.objectStore(STORE_NAME).get(key);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}
async function idbSet(key, value) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    tx.objectStore(STORE_NAME).put(value, key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}
function isValidPriceData(data) {
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    return false;
  }
  let valid = 0;
  for (const value of Object.values(data)) {
    if (!value || typeof value !== "object") {
      continue;
    }
    if ("input_cost_per_token" in value && "max_tokens" in value) {
      valid += 1;
      if (valid >= MIN_VALID_ENTRIES) {
        return true;
      }
    }
  }
  return false;
}
function setCatalogue(data, updatedAt) {
  byKey = /* @__PURE__ */ new Map();
  byTail = /* @__PURE__ */ new Map();
  for (const [key, value] of Object.entries(data ?? {})) {
    if (!value || typeof value !== "object") {
      continue;
    }
    const inputCost = Number(value.input_cost_per_token);
    const outputCost = Number(value.output_cost_per_token);
    if (!Number.isFinite(inputCost) && !Number.isFinite(outputCost)) {
      continue;
    }
    const entry = {
      key,
      inputCost: Number.isFinite(inputCost) ? inputCost : 0,
      outputCost: Number.isFinite(outputCost) ? outputCost : 0
    };
    const lowerKey = key.toLowerCase();
    byKey.set(lowerKey, entry);
    const tail = lowerKey.split("/").pop();
    if (tail && !byTail.has(tail)) {
      byTail.set(tail, entry);
    }
  }
  meta = { count: byKey.size, updatedAt: updatedAt ?? null };
}
function getPriceMeta() {
  return { ...meta };
}
function searchModels(query, limit = SEARCH_RESULT_LIMIT) {
  const needle = String(query ?? "").trim().toLowerCase();
  if (!byKey.size) {
    return [];
  }
  if (!needle) {
    return [...byKey.keys()].slice(0, limit);
  }
  const matches = [];
  for (const key of byKey.keys()) {
    const index = key.indexOf(needle);
    if (index === -1) {
      continue;
    }
    const tail = key.split("/").pop();
    const isTailHit = tail?.includes(needle) ?? false;
    matches.push({
      key,
      tailHit: isTailHit ? 0 : 1,
      position: index,
      length: key.length
    });
  }
  matches.sort((a, b) => a.tailHit - b.tailHit || a.position - b.position || a.length - b.length || a.key.localeCompare(b.key));
  return matches.slice(0, limit).map((item) => item.key);
}
async function loadCached() {
  try {
    const cached = await idbGet(CACHE_KEY);
    if (cached?.data && isValidPriceData(cached.data)) {
      setCatalogue(cached.data, cached.updatedAt ?? null);
    }
  } catch (error) {
    console.warn("[TokenMonitor] pricing cache load failed:", error);
  }
  return getPriceMeta();
}
async function updatePrices() {
  let lastError = null;
  for (const url of PRICE_URLS) {
    try {
      const response = await fetch(url, { cache: "no-store" });
      if (!response.ok) {
        lastError = new Error(`HTTP ${response.status}`);
        continue;
      }
      const data = await response.json();
      if (!isValidPriceData(data)) {
        lastError = new Error("invalid price data");
        continue;
      }
      const updatedAt = Date.now();
      setCatalogue(data, updatedAt);
      try {
        await idbSet(CACHE_KEY, { data, updatedAt });
      } catch (error) {
        console.warn("[TokenMonitor] pricing cache write failed:", error);
      }
      return { ok: true, ...getPriceMeta(), url };
    } catch (error) {
      lastError = error;
    }
  }
  return { ok: false, error: lastError?.message ?? "unknown error" };
}
function resolvePrice(model) {
  if (!byKey.size || !model) {
    return { found: false };
  }
  const query = String(model).trim().toLowerCase();
  if (!query) {
    return { found: false };
  }
  if (byKey.has(query)) {
    return { found: true, fuzzy: false, ...byKey.get(query) };
  }
  const tail = query.split("/").pop();
  if (tail && byTail.has(tail)) {
    return { found: true, fuzzy: false, ...byTail.get(tail) };
  }
  let best = null;
  for (const [key, entry] of byKey) {
    if (key.length < MIN_FUZZY_LENGTH) {
      continue;
    }
    if (query.includes(key) || key.includes(query)) {
      if (!best || key.length > best.matchLength) {
        best = { ...entry, matchLength: key.length };
      }
    }
  }
  if (best) {
    return { found: true, fuzzy: true, ...best };
  }
  return { found: false };
}
function computeCost({ input, output, model, rate = 1 }) {
  const price = resolvePrice(model);
  if (!price.found) {
    return { found: false, cost: null, usd: null, price };
  }
  const usd = (Number(input) || 0) * price.inputCost + (Number(output) || 0) * price.outputCost;
  return { found: true, cost: usd * (Number(rate) || 1), usd, price };
}

// src/combo.js
var MAX_OPTIONS = 40;
var MAX_OPTION_HEIGHT = 220;
var seq2 = 0;
function escapeHtml(value) {
  return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function createList() {
  const list = document.createElement("div");
  list.className = "tm-combo-list tm-hidden";
  list.id = `tm_combo_list_${++seq2}`;
  document.body.appendChild(list);
  return list;
}
function renderOptions(list, options, activeIndex) {
  if (options.length === 0) {
    list.innerHTML = '<div class="tm-combo-empty">价格库中无匹配模型</div>';
    return;
  }
  list.innerHTML = options.map((model, index) => {
    const label = escapeHtml(model);
    const className = index === activeIndex ? "tm-combo-option tm-active" : "tm-combo-option";
    return `<div class="${className}" data-model="${label}">${label}</div>`;
  }).join("");
}
function positionList(input, list) {
  const rect = input.getBoundingClientRect();
  const below = window.innerHeight - rect.bottom;
  const height = Math.min(MAX_OPTION_HEIGHT, list.scrollHeight);
  list.style.left = `${rect.left}px`;
  list.style.width = `${rect.width}px`;
  list.style.maxHeight = `${height}px`;
  if (below < height && rect.top > below) {
    list.style.top = "auto";
    list.style.bottom = `${window.innerHeight - rect.top}px`;
  } else {
    list.style.bottom = "auto";
    list.style.top = `${rect.bottom + 2}px`;
  }
}
function attachModelCombo(input, { onCommit } = {}) {
  const list = createList();
  let matches = [];
  let activeIndex = -1;
  const onWindowChange = () => close();
  input.setAttribute("autocomplete", "off");
  input.setAttribute("role", "combobox");
  input.setAttribute("aria-expanded", "false");
  input.setAttribute("aria-controls", list.id);
  input.setAttribute("aria-autocomplete", "list");
  function open() {
    positionList(input, list);
    list.classList.remove("tm-hidden");
    input.setAttribute("aria-expanded", "true");
  }
  function close() {
    list.classList.add("tm-hidden");
    input.setAttribute("aria-expanded", "false");
    activeIndex = -1;
  }
  function commit(value) {
    input.value = value;
    close();
    onCommit?.(value.trim());
  }
  function refresh() {
    matches = searchModels(input.value).slice(0, MAX_OPTIONS);
    activeIndex = matches.length ? 0 : -1;
    renderOptions(list, matches, activeIndex);
    open();
  }
  function selectActive() {
    if (activeIndex < 0 || activeIndex >= matches.length) {
      return;
    }
    commit(matches[activeIndex]);
  }
  function move(step) {
    if (matches.length === 0) {
      return;
    }
    activeIndex = (activeIndex + step + matches.length) % matches.length;
    renderOptions(list, matches, activeIndex);
    list.querySelector(".tm-active")?.scrollIntoView({ block: "nearest" });
  }
  input.addEventListener("input", refresh);
  input.addEventListener("focus", refresh);
  input.addEventListener("keydown", (event) => {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      move(1);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      move(-1);
    } else if (event.key === "Enter") {
      if (!list.classList.contains("tm-hidden")) {
        event.preventDefault();
        event.stopPropagation();
        selectActive();
      }
    } else if (event.key === "Escape") {
      close();
    }
  });
  list.addEventListener("mousedown", (event) => {
    const option = event.target.closest(".tm-combo-option");
    if (!option) {
      return;
    }
    event.preventDefault();
    commit(option.dataset.model);
  });
  input.addEventListener("blur", close);
  window.addEventListener("resize", onWindowChange);
  window.addEventListener("scroll", onWindowChange, true);
  function destroy() {
    close();
    window.removeEventListener("resize", onWindowChange);
    window.removeEventListener("scroll", onWindowChange, true);
    list.remove();
  }
  return { close, refresh, destroy };
}

// src/panel.js
var MODULE_NAME = "token_monitor";
var PANEL_ID = "token_monitor_panel";
var MENU_ID = "token_monitor_menu_entry";
var FAB_ID = "token_monitor_fab";
var MARKER_STORAGE_KEY = "token_monitor_markers";
var AUX_LABELS = { plot: "剧情推进", fill: "填表", other: "其他" };
var AUX_BADGE = { plot: "P", fill: "F", other: "O" };
var defaultSettings = Object.freeze({
  mainGenModel: "",
  plotModel: "",
  fillModel: "",
  rate: 1,
  classifyMode: "auto",
  panelVisible: false,
  panelPosition: null,
  collapsed: false
});
var AUX_MODEL_SETTINGS = { plot: "plotModel", fill: "fillModel", other: "fillModel" };
var bound = false;
var combos = [];
function ctx4() {
  return globalThis.SillyTavern?.getContext();
}
function getSettings() {
  const context = ctx4();
  if (!context?.extensionSettings) {
    return structuredClone(defaultSettings);
  }
  const store = context.extensionSettings;
  if (!store[MODULE_NAME]) {
    store[MODULE_NAME] = structuredClone(defaultSettings);
  }
  for (const key of Object.keys(defaultSettings)) {
    if (!Object.hasOwn(store[MODULE_NAME], key)) {
      store[MODULE_NAME][key] = defaultSettings[key];
    }
  }
  return store[MODULE_NAME];
}
function saveSettings() {
  const context = ctx4();
  if (typeof context?.saveSettingsDebounced === "function") {
    context.saveSettingsDebounced();
  }
}
function loadMarkers() {
  try {
    const parsed = JSON.parse(localStorage.getItem(MARKER_STORAGE_KEY));
    return {
      plotMarkers: Array.isArray(parsed?.plotMarkers) ? parsed.plotMarkers : [],
      fillMarkers: Array.isArray(parsed?.fillMarkers) ? parsed.fillMarkers : []
    };
  } catch {
    return { plotMarkers: [], fillMarkers: [] };
  }
}
function saveMarkers(markers) {
  try {
    localStorage.setItem(MARKER_STORAGE_KEY, JSON.stringify(markers));
  } catch (error) {
    console.warn("[TokenMonitor] cannot save markers:", error);
  }
}
function parseMarkers(text) {
  return String(text ?? "").split(/[\n,]+/).map((item) => item.trim()).filter(Boolean);
}
function detectCurrentModel() {
  const context = ctx4();
  try {
    const model = context?.getChatCompletionModel?.();
    if (typeof model === "string" && model) {
      return model;
    }
  } catch {
  }
  try {
    const model = context?.chatCompletionSettings?.openai_model;
    if (typeof model === "string" && model) {
      return model;
    }
  } catch {
  }
  return "";
}
function formatNumber(value) {
  if (!Number.isFinite(Number(value))) {
    return "—";
  }
  return Math.round(Number(value)).toLocaleString("en-US");
}
function formatCost(value, rate) {
  if (!Number.isFinite(value)) {
    return "—";
  }
  const symbol = Number(rate) === 1 ? "$" : "¥";
  const digits = Math.abs(value) > 0 && Math.abs(value) < 0.01 ? 4 : 2;
  return `${symbol}${value.toFixed(digits)}`;
}
function escapeHtml2(value) {
  return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function setText(id, text) {
  const element = document.getElementById(id);
  if (element) {
    element.textContent = text;
  }
}
function categoryCost(category, rate, fallbackModel) {
  const models = Object.entries(category?.byModel ?? {});
  if (models.length === 0) {
    return { cost: null, unknown: (category?.input ?? 0) > 0 || (category?.output ?? 0) > 0 };
  }
  let cost = 0;
  let anyFound = false;
  let unknown = false;
  let pricedAtFallback = false;
  for (const [model, value] of models) {
    const result = computeCost({ input: value.input, output: value.output, model, rate });
    if (result.found) {
      cost += result.cost;
      anyFound = true;
      continue;
    }
    const fallback = fallbackModel ? computeCost({ input: value.input, output: value.output, model: fallbackModel, rate }) : { found: false };
    if (fallback.found) {
      cost += fallback.cost;
      anyFound = true;
      pricedAtFallback = true;
    } else {
      unknown = true;
    }
  }
  return { cost: anyFound ? cost : null, unknown, fallback: pricedAtFallback };
}
function addMenuEntry() {
  if (document.getElementById(MENU_ID)) {
    return;
  }
  const menu = document.getElementById("extensionsMenu");
  if (menu) {
    const entry = document.createElement("div");
    entry.id = MENU_ID;
    entry.className = "list-group-item flex-container flexGap5";
    entry.innerHTML = '<div class="fa-solid fa-chart-column extensionsMenuExtensionButton"></div>Token 统计';
    entry.addEventListener("click", () => togglePanel());
    menu.appendChild(entry);
    return;
  }
  if (document.getElementById(FAB_ID)) {
    return;
  }
  const fab = document.createElement("div");
  fab.id = FAB_ID;
  fab.className = "fa-solid fa-chart-column";
  fab.title = "Token 统计";
  fab.addEventListener("click", () => togglePanel());
  document.body.appendChild(fab);
}
function buildPanelSkeleton() {
  const panel = document.createElement("div");
  panel.id = PANEL_ID;
  panel.classList.add("tm-hidden");
  panel.innerHTML = `
        <div class="tm-header">
            <span class="tm-title">Token 统计</span>
            <span class="tm-header-actions">
                <span class="tm-icon tm-collapse fa-solid fa-chevron-down" title="折叠/展开"></span>
                <span class="tm-icon tm-close fa-solid fa-xmark" title="隐藏"></span>
            </span>
        </div>
        <div class="tm-body">
            <div class="tm-main">
                <div class="tm-row"><span class="tm-label">主生成</span><span class="tm-value" id="tm-main-cost">—</span></div>
                <div class="tm-sub">
                    <span id="tm-main-in">in —</span>
                    <span id="tm-main-out">out —</span>
                    <span id="tm-main-total">total —</span>
                </div>
                <div class="tm-hint" id="tm-main-model"></div>
            </div>
            <div class="tm-aux" id="tm-aux"></div>
            <div class="tm-list">
                <div class="tm-messages-head">
                    <span>#</span><span>角色</span><span>in</span><span>out</span><span>aux</span>
                </div>
                <div class="tm-messages" id="tm-messages"></div>
            </div>
            <div class="tm-settings">
                <div class="tm-settings-head" id="tm-settings-toggle">
                    <span>设置</span>
                    <span class="tm-icon fa-solid fa-chevron-down"></span>
                </div>
                <div class="tm-settings-body tm-hidden" id="tm-settings-body">
                    <label class="tm-field">主生成模型
                        <input id="tm-set-model" class="text_pole" type="text" placeholder="留空则自动读取当前模型">
                    </label>
                    <label class="tm-field">剧情推进模型
                        <input id="tm-set-plot-model" class="text_pole" type="text" placeholder="留空则用拦截到的模型名">
                    </label>
                    <label class="tm-field">填表模型（含其他）
                        <input id="tm-set-fill-model" class="text_pole" type="text" placeholder="留空则用拦截到的模型名">
                    </label>
                    <label class="tm-field">汇率（rate=1 时按美元直显）
                        <input id="tm-set-rate" class="text_pole" type="number" min="0" step="0.01">
                    </label>
                    <label class="tm-field">分类模式
                        <select id="tm-set-mode" class="text_pole">
                            <option value="auto">自动（窗口 + 标记）</option>
                            <option value="markers-only">仅标记</option>
                        </select>
                    </label>
                    <label class="tm-field">剧情推进标记（逗号或换行分隔）
                        <textarea id="tm-set-plot-markers" class="text_pole" rows="2"></textarea>
                    </label>
                    <label class="tm-field">填表标记（逗号或换行分隔）
                        <textarea id="tm-set-fill-markers" class="text_pole" rows="2"></textarea>
                    </label>
                    <div class="tm-price-status" id="tm-price-status">未加载价格库</div>
                    <div class="tm-actions">
                        <div id="tm-update-prices" class="menu_button">更新价格库</div>
                        <div id="tm-recount" class="menu_button">重新统计</div>
                        <div id="tm-refresh" class="menu_button">刷新</div>
                        <div id="tm-clear" class="menu_button">清空本聊天</div>
                    </div>
                </div>
            </div>
        </div>`;
  return panel;
}
function bindPanelEvents(panel) {
  panel.querySelector(".tm-collapse").addEventListener("click", () => {
    const collapsed = panel.classList.toggle("tm-collapsed");
    const settings = getSettings();
    settings.collapsed = collapsed;
    saveSettings();
  });
  panel.querySelector(".tm-close").addEventListener("click", () => setPanelVisible(false));
  document.getElementById("tm-settings-toggle").addEventListener("click", () => {
    document.getElementById("tm-settings-body").classList.toggle("tm-hidden");
  });
  bindDrag(panel);
  bindSettingsInputs();
}
function bindDrag(panel) {
  const header = panel.querySelector(".tm-header");
  let dragging = false;
  let startX = 0;
  let startY = 0;
  let originX = 0;
  let originY = 0;
  header.addEventListener("mousedown", (event) => {
    if (event.target.closest(".tm-icon")) {
      return;
    }
    const rect = panel.getBoundingClientRect();
    dragging = true;
    startX = event.clientX;
    startY = event.clientY;
    originX = rect.left;
    originY = rect.top;
    panel.style.right = "auto";
    panel.style.bottom = "auto";
    panel.style.left = `${originX}px`;
    panel.style.top = `${originY}px`;
    event.preventDefault();
  });
  window.addEventListener("mousemove", (event) => {
    if (!dragging) {
      return;
    }
    const nextX = Math.max(0, originX + (event.clientX - startX));
    const nextY = Math.max(0, originY + (event.clientY - startY));
    panel.style.left = `${nextX}px`;
    panel.style.top = `${nextY}px`;
  });
  window.addEventListener("mouseup", () => {
    if (!dragging) {
      return;
    }
    dragging = false;
    const rect = panel.getBoundingClientRect();
    const settings = getSettings();
    settings.panelPosition = { x: Math.round(rect.left), y: Math.round(rect.top) };
    saveSettings();
  });
}
function bindSettingsInputs() {
  const settings = getSettings();
  const markers = loadMarkers();
  const modelInput = document.getElementById("tm-set-model");
  const plotModelInput = document.getElementById("tm-set-plot-model");
  const fillModelInput = document.getElementById("tm-set-fill-model");
  const rateInput = document.getElementById("tm-set-rate");
  const modeSelect = document.getElementById("tm-set-mode");
  const plotMarkers = document.getElementById("tm-set-plot-markers");
  const fillMarkers = document.getElementById("tm-set-fill-markers");
  modelInput.value = settings.mainGenModel ?? "";
  plotModelInput.value = settings.plotModel ?? "";
  fillModelInput.value = settings.fillModel ?? "";
  rateInput.value = String(settings.rate ?? 1);
  modeSelect.value = settings.classifyMode ?? "auto";
  plotMarkers.value = markers.plotMarkers.join("\n");
  fillMarkers.value = markers.fillMarkers.join("\n");
  const onModelChanged = (key) => (value) => {
    const current = getSettings();
    current[key] = value;
    saveSettings();
    refreshPanel();
  };
  const modelCommit = {
    "tm-set-model": onModelChanged("mainGenModel"),
    "tm-set-plot-model": onModelChanged("plotModel"),
    "tm-set-fill-model": onModelChanged("fillModel")
  };
  combos = [modelInput, plotModelInput, fillModelInput].map((input) => attachModelCombo(input, { onCommit: modelCommit[input.id] }));
  rateInput.addEventListener("input", () => {
    const current = getSettings();
    current.rate = Number(rateInput.value) || 1;
    saveSettings();
    refreshPanel();
  });
  modeSelect.addEventListener("change", () => {
    const current = getSettings();
    current.classifyMode = modeSelect.value === "markers-only" ? "markers-only" : "auto";
    saveSettings();
    applyClassification();
  });
  const onMarkersChanged = () => {
    saveMarkers({
      plotMarkers: parseMarkers(plotMarkers.value),
      fillMarkers: parseMarkers(fillMarkers.value)
    });
    applyClassification();
  };
  plotMarkers.addEventListener("input", onMarkersChanged);
  fillMarkers.addEventListener("input", onMarkersChanged);
  document.getElementById("tm-update-prices").addEventListener("click", handleUpdatePrices);
  document.getElementById("tm-refresh").addEventListener("click", () => {
    rescanAuxFrames();
    refreshPanel();
  });
  document.getElementById("tm-recount").addEventListener("click", async () => {
    await recomputeChat();
    refreshPanel();
  });
  document.getElementById("tm-clear").addEventListener("click", () => {
    clearChatTokenData();
    refreshPanel();
  });
}
function applyClassification() {
  const settings = getSettings();
  const markers = loadMarkers();
  setMarkerConfig({
    mode: settings.classifyMode ?? "auto",
    plotMarkers: markers.plotMarkers,
    fillMarkers: markers.fillMarkers
  });
}
async function handleUpdatePrices() {
  const button = document.getElementById("tm-update-prices");
  button?.classList.add("disabled");
  try {
    const result = await updatePrices();
    if (result.ok) {
      if (typeof toastr !== "undefined") {
        toastr.success(`价格库已更新（${result.count} 条）`);
      }
    } else if (typeof toastr !== "undefined") {
      toastr.error(`价格库更新失败：${result.error}`);
    }
  } finally {
    button?.classList.remove("disabled");
    updatePriceStatus();
    refreshPanel();
  }
}
function updatePriceStatus() {
  const element = document.getElementById("tm-price-status");
  if (!element) {
    return;
  }
  const meta2 = getPriceMeta();
  if (!meta2.count) {
    element.textContent = "未加载价格库";
    return;
  }
  const time = meta2.updatedAt ? new Date(meta2.updatedAt).toLocaleString() : "未知时间";
  element.textContent = `已加载 ${meta2.count} 条 · ${time}`;
}
function buildBadges(aux) {
  if (!aux) {
    return "—";
  }
  const badges = [];
  for (const category of Object.keys(AUX_BADGE)) {
    const data = aux[category];
    if (!data || !data.calls) {
      continue;
    }
    const title = `${AUX_LABELS[category]}: ${data.calls}次 · in ${formatNumber(data.input)} · out ${formatNumber(data.output)}`;
    badges.push(`<span class="tm-badge tm-badge-${category}" title="${escapeHtml2(title)}">${AUX_BADGE[category]}${data.calls}</span>`);
  }
  return badges.join("") || "—";
}
function renderMessages() {
  const container = document.getElementById("tm-messages");
  if (!container) {
    return;
  }
  const chat = ctx4()?.chat ?? [];
  const rows = [];
  chat.forEach((message, index) => {
    if (!message || message.is_system === true) {
      return;
    }
    const data = getMessageTokens(message);
    const role = message.is_user === true ? "用户" : message.name || "角色";
    const input = data && Number.isFinite(Number(data.input)) ? Number(data.input) : null;
    const output = data && Number.isFinite(Number(data.output)) ? Number(data.output) : null;
    rows.push(`
            <div class="tm-message-row" data-index="${index}">
                <span class="tm-message-index">${index + 1}</span>
                <span class="tm-message-role" title="${escapeHtml2(role)}">${escapeHtml2(role)}</span>
                <span class="tm-message-in">${input === null ? "—" : formatNumber(input)}</span>
                <span class="tm-message-out">${output === null ? "—" : formatNumber(output)}</span>
                <span class="tm-message-aux">${buildBadges(data?.aux)}</span>
            </div>`);
  });
  if (rows.length === 0) {
    container.innerHTML = '<div class="tm-empty">本聊天暂无统计数据</div>';
    return;
  }
  container.innerHTML = rows.join("");
  container.querySelectorAll(".tm-message-row").forEach((row) => {
    row.addEventListener("click", () => {
      const index = row.getAttribute("data-index");
      const target = document.querySelector(`.mes[mesid="${index}"]`);
      target?.scrollIntoView({ behavior: "smooth", block: "center" });
    });
  });
}
function renderAux(summary, rate, settings) {
  const container = document.getElementById("tm-aux");
  if (!container) {
    return;
  }
  container.innerHTML = Object.keys(AUX_LABELS).map((category) => {
    const data = summary.aux[category];
    const fallbackModel = settings[AUX_MODEL_SETTINGS[category]] ?? "";
    const { cost, unknown, fallback } = categoryCost(data, rate, fallbackModel);
    const costText = cost === null ? "—" : `${formatCost(cost, rate)}${unknown ? "*" : ""}`;
    const modelNote = fallback ? ` <i>按 ${escapeHtml2(fallbackModel)} 计价</i>` : "";
    return `
            <div class="tm-row tm-aux-row">
                <span class="tm-label">${AUX_LABELS[category]}</span>
                <span class="tm-aux-metrics">${data.calls}次 · in ${formatNumber(data.input)} · out ${formatNumber(data.output)} · <b>${costText}</b>${modelNote}</span>
            </div>`;
  }).join("");
}
function refreshPanel() {
  const panel = document.getElementById(PANEL_ID);
  if (!panel) {
    return;
  }
  const settings = getSettings();
  const rate = Number(settings.rate) || 1;
  const summary = computeChatSummary();
  const model = settings.mainGenModel || detectCurrentModel();
  const mainResult = model ? computeCost({ input: summary.totalInput, output: summary.totalOutput, model, rate }) : { found: false, cost: null };
  setText("tm-main-in", `in ${formatNumber(summary.totalInput)}`);
  setText("tm-main-out", `out ${formatNumber(summary.totalOutput)}`);
  setText("tm-main-total", `total ${formatNumber(summary.total)}`);
  setText("tm-main-cost", mainResult.found ? formatCost(mainResult.cost, rate) : "—");
  setText("tm-main-model", model ? `模型：${model}` : "未设置模型（不计算主生成成本）");
  renderAux(summary, rate, settings);
  renderMessages();
  updatePriceStatus();
}
function setPanelVisible(visible, { persist = true } = {}) {
  let panel = document.getElementById(PANEL_ID);
  if (!panel) {
    if (!visible) {
      return;
    }
    panel = buildPanelSkeleton();
    document.body.appendChild(panel);
    applySavedPosition(panel);
    if (getSettings().collapsed) {
      panel.classList.add("tm-collapsed");
    }
    bindPanelEvents(panel);
  }
  panel.classList.toggle("tm-hidden", !visible);
  if (persist) {
    const settings = getSettings();
    settings.panelVisible = Boolean(visible);
    saveSettings();
  }
  if (visible) {
    refreshPanel();
  }
}
function togglePanel() {
  const panel = document.getElementById(PANEL_ID);
  const currentlyVisible = panel ? !panel.classList.contains("tm-hidden") : Boolean(getSettings().panelVisible);
  setPanelVisible(!currentlyVisible);
}
function applySavedPosition(panel) {
  const position = getSettings().panelPosition;
  if (position && Number.isFinite(position.x) && Number.isFinite(position.y)) {
    panel.style.left = `${position.x}px`;
    panel.style.top = `${position.y}px`;
    panel.style.right = "auto";
    panel.style.bottom = "auto";
  }
}
function mountPanel() {
  if (bound) {
    return;
  }
  bound = true;
  addMenuEntry();
  applyClassification();
  for (const panel2 of document.querySelectorAll(`#${PANEL_ID}`)) {
    panel2.remove();
  }
  const panel = buildPanelSkeleton();
  document.body.appendChild(panel);
  applySavedPosition(panel);
  if (getSettings().collapsed) {
    panel.classList.add("tm-collapsed");
  }
  bindPanelEvents(panel);
  setPanelVisible(Boolean(getSettings().panelVisible), { persist: false });
}
function unmountPanel() {
  bound = false;
  for (const combo of combos) {
    combo.destroy();
  }
  combos = [];
  document.getElementById(PANEL_ID)?.remove();
  document.getElementById(MENU_ID)?.remove();
  document.getElementById(FAB_ID)?.remove();
}

// src/index.js
var started = false;
var subscriptions = [];
function ctx5() {
  return globalThis.SillyTavern?.getContext();
}
function resolveMessage(data) {
  const chat = ctx5()?.chat ?? [];
  if (Number.isInteger(data) && data >= 0 && data < chat.length) {
    return chat[data];
  }
  return chat.length ? chat[chat.length - 1] : null;
}
async function onMessageSent(data) {
  const message = resolveMessage(data);
  if (!message || message.is_user !== true) {
    return;
  }
  await updateMessageTokens(message);
  refreshPanel();
}
async function onMessageReceived(data) {
  const message = resolveMessage(data);
  if (!message || message.is_user === true) {
    return;
  }
  await updateMessageTokens(message, { usePendingInput: true });
  refreshPanel();
}
async function onMessageEdited(data) {
  const message = resolveMessage(data);
  if (!message) {
    return;
  }
  await updateMessageTokens(message);
  refreshPanel();
}
async function onMessageSwiped(data) {
  const message = resolveMessage(data);
  if (!message) {
    return;
  }
  await updateMessageTokens(message, { usePendingInput: true });
  refreshPanel();
}
function onChatChanged() {
  updateChatSummary();
  rescanAuxFrames();
  refreshPanel();
}
function onGenerationStopped() {
  clearPendingInput();
}
function subscribe(eventSource, eventType, handler) {
  if (!eventType || typeof eventSource?.on !== "function") {
    return;
  }
  eventSource.on(eventType, handler);
  subscriptions.push([eventType, handler]);
}
function registerEvents() {
  const context = ctx5();
  const eventSource = context?.eventSource;
  const eventTypes = context?.eventTypes;
  if (!eventSource || !eventTypes || subscriptions.length) {
    return;
  }
  subscribe(eventSource, eventTypes.APP_READY, () => mountPanel());
  subscribe(eventSource, eventTypes.MESSAGE_SENT, onMessageSent);
  subscribe(eventSource, eventTypes.MESSAGE_RECEIVED, onMessageReceived);
  subscribe(eventSource, eventTypes.MESSAGE_EDITED, onMessageEdited);
  subscribe(eventSource, eventTypes.MESSAGE_SWIPED, onMessageSwiped);
  subscribe(eventSource, eventTypes.MESSAGE_DELETED, onChatChanged);
  subscribe(eventSource, eventTypes.CHAT_CHANGED, onChatChanged);
  subscribe(eventSource, eventTypes.GENERATION_STOPPED, onGenerationStopped);
}
function unregisterEvents() {
  const eventSource = ctx5()?.eventSource;
  for (const [eventType, handler] of subscriptions) {
    eventSource?.removeListener?.(eventType, handler);
  }
  subscriptions = [];
}
function start() {
  if (started) {
    return;
  }
  started = true;
  initTokenTracking();
  installAuxFetchInterceptor();
  void loadCached();
  registerEvents();
}
function stop() {
  if (!started) {
    return;
  }
  started = false;
  unregisterEvents();
  uninstallAuxFetchInterceptor();
  unmountPanel();
}
function onEnable() {
  start();
}
function onDisable() {
  stop();
}
function onClean() {
  clearAllTokenData();
  stop();
}
start();
export {
  onClean,
  onDisable,
  onEnable,
  start,
  stop
};
