/* Generated by esbuild from src/. Edit files in src/ and run: npm run build */

// src/tokens.js
var QUIET_TYPES = /* @__PURE__ */ new Set(["quiet"]);
var TOKEN_CACHE_MAX = 400;
var tokenCache = /* @__PURE__ */ new Map();
var pendingGenType = null;
function ctx() {
  return globalThis.SillyTavern?.getContext();
}
function hashString(text) {
  let hash = 5381;
  for (let i = 0; i < text.length; i++) {
    hash = (hash << 5) + hash + text.charCodeAt(i) | 0;
  }
  return (hash >>> 0).toString(36);
}
function initTokenTracking() {
  globalThis.tokenMonitorInterceptor = function(_chat, _contextSize, _abort, type) {
    pendingGenType = typeof type === "string" && type ? type : "normal";
  };
}
function takeGenerationType() {
  const type = pendingGenType;
  pendingGenType = null;
  return type;
}
function isQuietType(type) {
  return QUIET_TYPES.has(type);
}
async function countTextAsync(text) {
  const context = ctx();
  if (!context || typeof context.getTokenCountAsync !== "function") {
    return null;
  }
  try {
    const count = await context.getTokenCountAsync(text ?? "");
    return Number.isFinite(count) ? count : null;
  } catch (error) {
    console.error("[TokenMonitor] token count failed:", error);
    return null;
  }
}
async function countTokensCached(text) {
  const value = text ?? "";
  const key = `${hashString(value)}:${value.length}`;
  if (tokenCache.has(key)) {
    const cached = tokenCache.get(key);
    tokenCache.delete(key);
    tokenCache.set(key, cached);
    return cached;
  }
  const count = await countTextAsync(value);
  if (count !== null) {
    tokenCache.set(key, count);
    if (tokenCache.size > TOKEN_CACHE_MAX) {
      const oldest = tokenCache.keys().next().value;
      tokenCache.delete(oldest);
    }
  }
  return count;
}
async function countMessageTokens(message) {
  if (typeof message === "string") {
    return countTokensCached(message);
  }
  let total = 0;
  const content = message?.content ?? "";
  if (typeof content === "string") {
    total += await countTokensCached(content) ?? 0;
  } else if (Array.isArray(content)) {
    for (const part of content) {
      if (typeof part?.text === "string") {
        total += await countTokensCached(part.text) ?? 0;
      }
    }
  } else if (content != null) {
    total += await countTokensCached(JSON.stringify(content)) ?? 0;
  }
  if (Array.isArray(message?.tool_calls) && message.tool_calls.length > 0) {
    total += await countTokensCached(JSON.stringify(message.tool_calls)) ?? 0;
  }
  if (typeof message?.name === "string" && message.name) {
    total += await countTokensCached(message.name) ?? 0;
  }
  return total;
}
async function countMsgTokens(messages) {
  let total = 0;
  for (const message of messages ?? []) {
    const count = await countMessageTokens(message);
    total += count !== null ? count : 0;
  }
  return total;
}
async function countRequestTokens(generateData) {
  const raw = generateData?.prompt ?? generateData?.messages ?? generateData?.input ?? null;
  if (Array.isArray(raw)) {
    return countMsgTokens(raw);
  }
  if (typeof raw === "string" && raw.length > 0) {
    return countTokensCached(raw);
  }
  return null;
}
function firstFinite(...values) {
  for (const value of values) {
    if (value === null || value === void 0) {
      continue;
    }
    const num = Number(value);
    if (Number.isFinite(num)) {
      return num;
    }
  }
  return null;
}
function extractUsageTokens(usage) {
  if (!usage || typeof usage !== "object") {
    return null;
  }
  const details = usage.prompt_tokens_details ?? usage.input_tokens_details ?? {};
  return {
    input: firstFinite(usage.prompt_tokens, usage.input_tokens),
    output: firstFinite(usage.completion_tokens, usage.output_tokens),
    cachedInput: firstFinite(
      usage.cache_read_input_tokens,
      usage.prompt_cache_hit_tokens,
      usage.cached_tokens,
      details.cached_tokens,
      usage.cached_content_token_count,
      usage.cachedContentTokenCount
    ) ?? 0,
    cacheWriteInput: firstFinite(usage.cache_creation_input_tokens) ?? 0
  };
}

// src/store.js
var DATA_KEY = "token_monitor";
var UNATTRIBUTED_KEY = "token_monitor_unattributed";
var REQUESTS_KEY = "token_monitor_requests";
var SCHEMA_VERSION = 2;
var SAVE_DEBOUNCE_MS = 1500;
var AUX_CATEGORIES = ["plot", "fill", "other"];
var PLOT_MATCH_RETRIES = 40;
var PLOT_MATCH_INTERVAL_MS = 1e3;
var FILL_TEXT_MIN_LENGTH = 60;
var TEXT_MATCH_MIN_LENGTH = 20;
var saveTimer = null;
function ctx2() {
  return globalThis.SillyTavern?.getContext();
}
function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function toNumber(value) {
  const num = Number(value);
  return Number.isFinite(num) ? num : 0;
}
function isTrackable(message) {
  return Boolean(message) && typeof message === "object" && message.is_system !== true && typeof message.mes === "string";
}
function ownTextOf(message) {
  const mes = typeof message?.mes === "string" ? message.mes : "";
  if (message?.is_user === true) {
    return mes;
  }
  const reasoning = message?.extra?.reasoning;
  return `${typeof reasoning === "string" ? reasoning : ""}${mes}`;
}
function emptyCategory() {
  return { calls: 0, input: 0, output: 0, byModel: {} };
}
function emptyAux() {
  return { plot: emptyCategory(), fill: emptyCategory(), other: emptyCategory() };
}
function normalizeByModel(byModel) {
  const result = {};
  if (!byModel || typeof byModel !== "object") {
    return result;
  }
  for (const [model, value] of Object.entries(byModel)) {
    result[model] = {
      calls: toNumber(value?.calls),
      input: toNumber(value?.input),
      output: toNumber(value?.output)
    };
  }
  return result;
}
function normalizeAux(aux) {
  const result = emptyAux();
  if (!aux || typeof aux !== "object") {
    return result;
  }
  for (const category of AUX_CATEGORIES) {
    const source = aux[category];
    if (!source || typeof source !== "object") {
      continue;
    }
    result[category] = {
      calls: toNumber(source.calls),
      input: toNumber(source.input),
      output: toNumber(source.output),
      byModel: normalizeByModel(source.byModel)
    };
  }
  return result;
}
function addToCategory(category, { model, input, output }) {
  category.calls += 1;
  category.input += toNumber(input);
  category.output += toNumber(output);
  const key = model || "";
  if (!key) {
    return;
  }
  const entry = category.byModel[key] ?? { calls: 0, input: 0, output: 0 };
  entry.calls += 1;
  entry.input += toNumber(input);
  entry.output += toNumber(output);
  category.byModel[key] = entry;
}
function buildData({ input, output, aux, ts }) {
  return {
    v: SCHEMA_VERSION,
    input: input ?? null,
    output: output ?? null,
    total: (input ?? 0) + (output ?? 0),
    aux: normalizeAux(aux),
    ts: ts ?? Date.now()
  };
}
function getMessageTokens(message) {
  return message?.extra?.[DATA_KEY] ?? null;
}
function attach(message, data) {
  if (!message.extra || typeof message.extra !== "object") {
    message.extra = {};
  }
  message.extra[DATA_KEY] = data;
}
function getRequestLog() {
  const context = ctx2();
  if (!context?.chatMetadata) {
    return [];
  }
  if (!Array.isArray(context.chatMetadata[REQUESTS_KEY])) {
    context.chatMetadata[REQUESTS_KEY] = [];
  }
  return context.chatMetadata[REQUESTS_KEY];
}
function listRequests() {
  return getRequestLog().map((entry) => ({ ...entry, floor: Number.isInteger(entry.floor) ? entry.floor : null })).sort((a, b) => a.ts - b.ts || a.id - b.id);
}
function appendRequest(record) {
  const context = ctx2();
  if (!context?.chatMetadata || !record) {
    return null;
  }
  const log = getRequestLog();
  const lastId = log.length ? toNumber(log[log.length - 1].id) : 0;
  const entry = {
    id: lastId + 1,
    ts: toNumber(record.ts) || Date.now(),
    kind: record.kind,
    floor: Number.isInteger(record.floor) ? record.floor : null,
    model: typeof record.model === "string" ? record.model : "",
    input: Number.isFinite(Number(record.input)) && record.input !== null ? Number(record.input) : null,
    output: Number.isFinite(Number(record.output)) && record.output !== null ? Number(record.output) : null,
    cachedInput: Math.max(0, toNumber(record.cachedInput)),
    cacheWriteInput: Math.max(0, toNumber(record.cacheWriteInput))
  };
  log.push(entry);
  scheduleSave();
  return entry;
}
function patchRequest(id, fields) {
  const entry = getRequestLog().find((item) => toNumber(item.id) === toNumber(id));
  if (!entry || !fields) {
    return null;
  }
  if ("floor" in fields) {
    entry.floor = Number.isInteger(fields.floor) ? fields.floor : null;
  }
  if ("input" in fields) {
    entry.input = Number.isFinite(Number(fields.input)) ? Number(fields.input) : null;
  }
  if ("output" in fields) {
    entry.output = Number.isFinite(Number(fields.output)) ? Number(fields.output) : null;
  }
  if ("cachedInput" in fields) {
    entry.cachedInput = Math.max(0, toNumber(fields.cachedInput));
  }
  if ("cacheWriteInput" in fields) {
    entry.cacheWriteInput = Math.max(0, toNumber(fields.cacheWriteInput));
  }
  if ("model" in fields && typeof fields.model === "string") {
    entry.model = fields.model;
  }
  scheduleSave();
  return entry;
}
function computeRequestSummary() {
  const main = { calls: 0, input: 0, output: 0, unknownInput: false };
  const aux = emptyAux();
  for (const entry of getRequestLog()) {
    const input = entry.input === null ? 0 : toNumber(entry.input);
    const output = entry.output === null ? 0 : toNumber(entry.output);
    if (entry.kind === "main") {
      main.calls += 1;
      main.input += input;
      main.output += output;
      if (entry.input === null) {
        main.unknownInput = true;
      }
      continue;
    }
    const category = aux[entry.kind];
    if (category) {
      addToCategory(category, { model: entry.model, input, output });
    }
  }
  return {
    main,
    aux,
    totalInput: main.input,
    totalOutput: main.output,
    total: main.input + main.output
  };
}
async function updateMessageTokens(message, { input, output } = {}) {
  if (!isTrackable(message)) {
    return null;
  }
  const existing = getMessageTokens(message) ?? {};
  const own = await countTextAsync(ownTextOf(message));
  const isUser = message.is_user === true;
  const resolvedInput = input !== void 0 ? input : isUser ? own : existing.input ?? null;
  const resolvedOutput = output !== void 0 ? output : isUser ? 0 : own;
  const data = buildData({ input: resolvedInput, output: resolvedOutput, aux: existing.aux, ts: existing.ts });
  attach(message, data);
  scheduleSave();
  return data;
}
async function recomputeChat() {
  const context = ctx2();
  const chat = context?.chat ?? [];
  for (const message of chat) {
    if (!isTrackable(message)) {
      continue;
    }
    const existing = getMessageTokens(message) ?? {};
    const own = await countTextAsync(ownTextOf(message));
    const isUser = message.is_user === true;
    const input = isUser ? own : existing.input ?? null;
    const output = isUser ? 0 : own;
    attach(message, buildData({ input, output, aux: existing.aux, ts: existing.ts }));
  }
  const lastMainByFloor = /* @__PURE__ */ new Map();
  for (const entry of getRequestLog()) {
    if (entry.kind === "main" && Number.isInteger(entry.floor)) {
      lastMainByFloor.set(entry.floor, entry);
    }
  }
  for (const [floor, entry] of lastMainByFloor) {
    const message = chat[floor];
    if (!isTrackable(message)) {
      continue;
    }
    const own = await countTextAsync(ownTextOf(message));
    if (own !== null) {
      entry.output = own;
    }
  }
  await flushSave();
}
function textMatches(a, b) {
  if (!a || !b) {
    return false;
  }
  if (a === b) {
    return true;
  }
  if (a.length >= TEXT_MATCH_MIN_LENGTH && b.includes(a)) {
    return true;
  }
  if (b.length >= TEXT_MATCH_MIN_LENGTH && a.includes(b)) {
    return true;
  }
  return false;
}
function findPlotMessage(responseText, minIndex = 0) {
  if (!responseText) {
    return null;
  }
  const chat = ctx2()?.chat ?? [];
  for (let i = chat.length - 1; i >= minIndex; i--) {
    const message = chat[i];
    if (!message || message.is_system === true) {
      continue;
    }
    if (textMatches(message.qrf_plot, responseText)) {
      return message;
    }
    const tasks = message.qrf_plot_tasks;
    if (tasks && typeof tasks === "object") {
      for (const value of Object.values(tasks)) {
        if (typeof value === "string" && textMatches(value, responseText)) {
          return message;
        }
      }
    }
  }
  return null;
}
function hasPlotMatch(responseText) {
  return Boolean(findPlotMessage(responseText));
}
function findTriggerUserMessage() {
  const chat = ctx2()?.chat ?? [];
  for (let i = chat.length - 1; i >= 0; i--) {
    const message = chat[i];
    if (message && message.is_system !== true && message.is_user === true) {
      return message;
    }
  }
  return null;
}
function findDeepestMatchingAiFloor(requestTexts) {
  const chat = ctx2()?.chat ?? [];
  for (let i = chat.length - 1; i >= 0; i--) {
    const message = chat[i];
    if (!message || message.is_system === true) {
      continue;
    }
    const mes = typeof message.mes === "string" ? message.mes : "";
    if (mes.length < FILL_TEXT_MIN_LENGTH) {
      continue;
    }
    if (requestTexts.some((text) => text.includes(mes) || mes.includes(text))) {
      if (message.is_user !== true) {
        return message;
      }
    }
  }
  return null;
}
function findLatestAiFloor() {
  const chat = ctx2()?.chat ?? [];
  for (let i = chat.length - 1; i >= 0; i--) {
    const message = chat[i];
    if (message && message.is_system !== true && message.is_user !== true) {
      return message;
    }
  }
  return null;
}
function indexOfMessage(message) {
  const chat = ctx2()?.chat ?? [];
  const index = chat.indexOf(message);
  return index >= 0 ? index : null;
}
function addAuxToMessage(message, category, record) {
  if (!isTrackable(message)) {
    addUnattributed(category, record);
    return;
  }
  const existing = getMessageTokens(message) ?? {};
  const data = buildData({
    input: existing.input ?? null,
    output: existing.output ?? null,
    aux: existing.aux,
    ts: existing.ts
  });
  addToCategory(data.aux[category], record);
  attach(message, data);
}
function addUnattributed(category, record) {
  const context = ctx2();
  if (!context?.chatMetadata) {
    return;
  }
  const bucket = normalizeAux(context.chatMetadata[UNATTRIBUTED_KEY]);
  addToCategory(bucket[category], record);
  context.chatMetadata[UNATTRIBUTED_KEY] = bucket;
  if (typeof context.saveMetadataDebounced === "function") {
    context.saveMetadataDebounced();
  }
}
async function recordPlotUsage(record) {
  const findMatch = () => {
    const minIndex = indexOfMessage(findTriggerUserMessage()) ?? 0;
    return findPlotMessage(record.responseText, minIndex);
  };
  let target = findMatch();
  if (!target && record.responseText) {
    for (let attempt = 0; attempt < PLOT_MATCH_RETRIES && !target; attempt++) {
      await delay(PLOT_MATCH_INTERVAL_MS);
      target = findMatch();
    }
  }
  if (!target) {
    target = findTriggerUserMessage();
  }
  if (!target) {
    addUnattributed("plot", record);
    return;
  }
  patchRequest(record.logId, { floor: indexOfMessage(target) });
  addAuxToMessage(target, "plot", record);
  scheduleSave();
}
function recordFillUsage(record) {
  const requestTexts = (record.requestTexts ?? []).map((item) => item?.content).filter((text) => typeof text === "string" && text.length > 0);
  const target = findDeepestMatchingAiFloor(requestTexts) ?? findLatestAiFloor();
  if (!target) {
    addUnattributed("fill", record);
    return;
  }
  patchRequest(record.logId, { floor: indexOfMessage(target) });
  addAuxToMessage(target, "fill", record);
  scheduleSave();
}
async function recordAuxUsage(record) {
  if (!record || !AUX_CATEGORIES.includes(record.category)) {
    return;
  }
  if (record.category === "plot") {
    await recordPlotUsage(record);
    return;
  }
  if (record.category === "fill") {
    recordFillUsage(record);
    return;
  }
  addUnattributed(record.category, record);
}
function updateChatSummary() {
  const context = ctx2();
  if (!context?.chatMetadata) {
    return;
  }
  const summary = computeRequestSummary();
  context.chatMetadata[DATA_KEY] = {
    v: SCHEMA_VERSION,
    totalInput: summary.main.input,
    totalOutput: summary.main.output,
    calls: summary.main.calls,
    aux: summary.aux,
    updatedAt: Date.now()
  };
  if (typeof context.saveMetadataDebounced === "function") {
    context.saveMetadataDebounced();
  }
}
function scheduleSave() {
  if (saveTimer) {
    clearTimeout(saveTimer);
  }
  saveTimer = setTimeout(() => {
    saveTimer = null;
    void flushSave();
  }, SAVE_DEBOUNCE_MS);
}
async function flushSave() {
  const context = ctx2();
  updateChatSummary();
  if (context && typeof context.saveChat === "function") {
    try {
      await context.saveChat();
    } catch (error) {
      console.error("[TokenMonitor] save chat failed:", error);
    }
  }
}
function clearChatTokenData() {
  const context = ctx2();
  const chat = context?.chat ?? [];
  for (const message of chat) {
    if (message?.extra && Object.hasOwn(message.extra, DATA_KEY)) {
      delete message.extra[DATA_KEY];
    }
  }
  if (context?.chatMetadata) {
    delete context.chatMetadata[DATA_KEY];
    delete context.chatMetadata[UNATTRIBUTED_KEY];
    delete context.chatMetadata[REQUESTS_KEY];
  }
  void flushSave();
}
function clearAllTokenData() {
  clearChatTokenData();
}

// src/interceptor.js
var GENERATE_PATH = "/api/backends/chat-completions/generate";
var FILL_WINDOW_TTL_MS = 12e4;
var PLOT_WINDOW_TTL_MS = 18e4;
var AUTOCARD_RETRY_INTERVAL_MS = 5e3;
var AUTOCARD_RETRY_MAX = 60;
var classification = { mode: "auto", plotMarkers: [], fillMarkers: [] };
var observer = { instance: null };
var patchedWindows = /* @__PURE__ */ new Map();
var plotWindowOpen = false;
var plotWindowTimer = null;
var fillWindowOpen = false;
var fillWindowTimer = null;
var stHandlers = null;
var autoCardCallback = null;
var autoCardRetryTimer = null;
var autoCardRetryCount = 0;
var seq = 0;
function ctx3() {
  return globalThis.SillyTavern?.getContext();
}
function getChatLength() {
  const chat = ctx3()?.chat;
  return Array.isArray(chat) ? chat.length : 0;
}
function openFillWindow() {
  fillWindowOpen = true;
  if (fillWindowTimer) {
    clearTimeout(fillWindowTimer);
  }
  fillWindowTimer = setTimeout(() => {
    fillWindowOpen = false;
    fillWindowTimer = null;
  }, FILL_WINDOW_TTL_MS);
}
function openPlotWindow() {
  plotWindowOpen = true;
  if (plotWindowTimer) {
    clearTimeout(plotWindowTimer);
  }
  plotWindowTimer = setTimeout(() => {
    plotWindowOpen = false;
    plotWindowTimer = null;
  }, PLOT_WINDOW_TTL_MS);
}
function closePlotWindow() {
  plotWindowOpen = false;
  if (plotWindowTimer) {
    clearTimeout(plotWindowTimer);
    plotWindowTimer = null;
  }
}
function installClassifierEvents() {
  const context = ctx3();
  const eventSource = context?.eventSource;
  const eventTypes = context?.eventTypes;
  if (!eventSource || !eventTypes || stHandlers) {
    return;
  }
  stHandlers = {
    plotOpen: () => openPlotWindow(),
    plotClose: () => closePlotWindow(),
    fillOpen: () => openFillWindow(),
    chatChanged: () => scheduleAutoCardRetry(true)
  };
  eventSource.on(eventTypes.GENERATION_AFTER_COMMANDS, stHandlers.plotOpen);
  eventSource.on(eventTypes.GENERATION_STARTED, stHandlers.plotClose);
  eventSource.on(eventTypes.GENERATION_ENDED, stHandlers.fillOpen);
  if (eventTypes.CHAT_CHANGED) {
    eventSource.on(eventTypes.CHAT_CHANGED, stHandlers.chatChanged);
  }
}
function uninstallClassifierEvents() {
  const context = ctx3();
  const eventSource = context?.eventSource;
  const eventTypes = context?.eventTypes;
  if (eventSource && eventTypes && stHandlers) {
    eventSource.removeListener?.(eventTypes.GENERATION_AFTER_COMMANDS, stHandlers.plotOpen);
    eventSource.removeListener?.(eventTypes.GENERATION_STARTED, stHandlers.plotClose);
    eventSource.removeListener?.(eventTypes.GENERATION_ENDED, stHandlers.fillOpen);
    if (eventTypes.CHAT_CHANGED) {
      eventSource.removeListener?.(eventTypes.CHAT_CHANGED, stHandlers.chatChanged);
    }
  }
  stHandlers = null;
}
function getAutoCardApi() {
  return globalThis.AutoCardUpdaterAPI ?? globalThis.topLevelWindow?.AutoCardUpdaterAPI ?? null;
}
function registerAutoCardHooks() {
  const api = getAutoCardApi();
  if (!api || typeof api.registerTableFillStartCallback !== "function") {
    return false;
  }
  if (autoCardCallback) {
    return true;
  }
  autoCardCallback = () => openFillWindow();
  try {
    api.registerTableFillStartCallback(autoCardCallback);
    return true;
  } catch (error) {
    console.warn("[TokenMonitor] registerTableFillStartCallback failed:", error);
    autoCardCallback = null;
    return false;
  }
}
function unregisterAutoCardHooks() {
  const api = getAutoCardApi();
  if (api && autoCardCallback && typeof api.unregisterTableFillStartCallback === "function") {
    try {
      api.unregisterTableFillStartCallback(autoCardCallback);
    } catch (error) {
      console.warn("[TokenMonitor] unregisterTableFillStartCallback failed:", error);
    }
  }
  autoCardCallback = null;
}
function stopAutoCardRetry() {
  if (autoCardRetryTimer) {
    clearInterval(autoCardRetryTimer);
    autoCardRetryTimer = null;
  }
}
function scheduleAutoCardRetry(reset = false) {
  if (reset) {
    autoCardRetryCount = 0;
  }
  if (registerAutoCardHooks()) {
    stopAutoCardRetry();
    return;
  }
  if (autoCardRetryTimer) {
    return;
  }
  autoCardRetryTimer = setInterval(() => {
    autoCardRetryCount += 1;
    if (registerAutoCardHooks() || autoCardRetryCount >= AUTOCARD_RETRY_MAX) {
      stopAutoCardRetry();
    }
  }, AUTOCARD_RETRY_INTERVAL_MS);
}
function collectSameOriginWindows(rootDocument, result) {
  let iframes;
  try {
    iframes = rootDocument.querySelectorAll("iframe");
  } catch {
    return result;
  }
  iframes.forEach((iframe) => {
    if (!iframe.__tokenMonitorLoadBound) {
      iframe.__tokenMonitorLoadBound = true;
      iframe.addEventListener("load", () => scanIframes());
    }
    let win = null;
    try {
      win = iframe.contentWindow;
    } catch {
      win = null;
    }
    if (!win) {
      return;
    }
    try {
      if (!win.document) {
        return;
      }
    } catch {
      return;
    }
    if (!result.includes(win)) {
      result.push(win);
    }
    try {
      collectSameOriginWindows(win.document, result);
    } catch {
    }
  });
  return result;
}
function patchWindow(win, isMainWindow = false) {
  if (!win || win.__tokenMonitorAuxHooked) {
    return;
  }
  if (typeof win.fetch !== "function") {
    return;
  }
  const original = win.fetch.bind(win);
  patchedWindows.set(win, win.fetch);
  win.fetch = createWrappedFetch(original, isMainWindow);
  win.__tokenMonitorAuxHooked = true;
}
function pruneClosedWindows() {
  for (const win of [...patchedWindows.keys()]) {
    try {
      if (win.closed) {
        patchedWindows.delete(win);
      }
    } catch {
      patchedWindows.delete(win);
    }
  }
}
function scanIframes() {
  if (typeof document === "undefined") {
    return;
  }
  pruneClosedWindows();
  for (const win of collectSameOriginWindows(document, [])) {
    patchWindow(win);
  }
}
function isGenerateUrl(url) {
  if (typeof url !== "string" || !url) {
    return false;
  }
  const path = url.split("?")[0].split("#")[0];
  return path.endsWith(GENERATE_PATH);
}
function contentToText(content) {
  if (typeof content === "string") {
    return content;
  }
  if (Array.isArray(content)) {
    return content.map((part) => typeof part?.text === "string" ? part.text : "").join("");
  }
  if (content == null) {
    return "";
  }
  return String(content);
}
function extractRequestTexts(body) {
  return (body.messages ?? []).map((message) => ({
    role: message?.role,
    content: contentToText(message?.content)
  }));
}
function matchMarkers(text, markers) {
  return markers.some((marker) => marker && text.includes(marker));
}
function classifyAtRequest(body) {
  const requestText = extractRequestTexts(body).map((item) => item.content).join("\n");
  if (matchMarkers(requestText, classification.plotMarkers)) {
    return "plot";
  }
  if (matchMarkers(requestText, classification.fillMarkers)) {
    return "fill";
  }
  if (classification.mode === "markers-only") {
    return null;
  }
  if (fillWindowOpen) {
    return "fill";
  }
  if (plotWindowOpen) {
    return "plot";
  }
  return null;
}
function resolveCategory(record) {
  if (record.categoryHint) {
    return record.categoryHint;
  }
  if (hasPlotMatch(record.responseText)) {
    return "plot";
  }
  return "other";
}
async function readSse(response) {
  let text = "";
  let usage = null;
  const reader = response.body?.getReader?.();
  if (!reader) {
    return { text, usage };
  }
  const decoder = new TextDecoder();
  let buffer = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("data:")) {
        continue;
      }
      const payload = trimmed.slice(5).trim();
      if (!payload || payload === "[DONE]") {
        continue;
      }
      try {
        const chunk = JSON.parse(payload);
        const delta = chunk?.choices?.[0]?.delta?.content;
        if (typeof delta === "string") {
          text += delta;
        }
        if (chunk?.usage) {
          usage = chunk.usage;
        }
      } catch {
      }
    }
  }
  return { text, usage };
}
function collectResponse(response, onDone) {
  const clone = response.clone();
  const contentType = clone.headers?.get?.("content-type") ?? "";
  if (contentType.includes("text/event-stream")) {
    void readSse(clone).then(({ text, usage }) => onDone({ text, usage })).catch(() => onDone({ text: "", usage: null }));
    return;
  }
  void clone.json().then((payload) => {
    const content = payload?.choices?.[0]?.message?.content;
    onDone({
      text: typeof content === "string" ? content : content == null ? "" : JSON.stringify(content),
      usage: payload?.usage ?? null
    });
  }).catch(() => onDone({ text: "", usage: null }));
}
function createWrappedFetch(original, isMainWindow) {
  return async function tokenMonitorFetch(input, init) {
    const url = typeof input === "string" ? input : input?.url ?? "";
    let body = null;
    try {
      const raw = init?.body ?? (input && typeof input === "object" ? input.body : null);
      if (typeof raw === "string") {
        body = JSON.parse(raw);
      }
    } catch {
      body = null;
    }
    const interceptable = isGenerateUrl(url) && body && Array.isArray(body.messages) && body.messages.length > 0;
    const mainCapture = isMainWindow && interceptable && typeof globalThis.__tokenMonitorClaimMainFetch === "function" && globalThis.__tokenMonitorClaimMainFetch() ? { model: typeof body.model === "string" ? body.model : "" } : null;
    const record = !isMainWindow && interceptable ? {
      seq: ++seq,
      ts: Date.now(),
      model: body.model || "",
      requestTexts: extractRequestTexts(body),
      stream: Boolean(body.stream),
      responseText: "",
      usage: null,
      categoryHint: classifyAtRequest(body),
      chatLenAt: getChatLength()
    } : null;
    const response = await original(input, init);
    if (mainCapture) {
      collectResponse(response, ({ text, usage }) => {
        if (typeof globalThis.__tokenMonitorDeliverMainUsage === "function") {
          void globalThis.__tokenMonitorDeliverMainUsage({ text, usage, model: mainCapture.model });
        }
      });
    }
    if (record) {
      try {
        collectResponse(response, ({ text, usage }) => {
          record.responseText = text;
          record.usage = usage;
          ingest(record);
        });
      } catch (error) {
        console.error("[TokenMonitor] aux capture failed:", error);
      }
    }
    return response;
  };
}
function ingest(record) {
  if (typeof globalThis.__tokenMonitorIngest === "function") {
    void globalThis.__tokenMonitorIngest(record);
  }
}
async function handleIngest(record) {
  try {
    const usage = extractUsageTokens(record.usage);
    const input = usage && usage.input !== null ? usage.input : await countMsgTokens(record.requestTexts);
    const output = usage && usage.output !== null ? usage.output : await countTokensCached(record.responseText ?? "");
    const cachedInput = usage?.cachedInput ?? 0;
    const cacheWriteInput = usage?.cacheWriteInput ?? 0;
    const category = resolveCategory(record);
    const entry = appendRequest({
      kind: category,
      floor: null,
      model: record.model,
      input: input ?? 0,
      output: output ?? 0,
      cachedInput,
      cacheWriteInput,
      ts: record.ts
    });
    await recordAuxUsage({
      category,
      logId: entry?.id,
      model: record.model,
      input: input ?? 0,
      output: output ?? 0,
      chatLenAt: record.chatLenAt,
      responseText: record.responseText,
      requestTexts: record.requestTexts,
      ts: record.ts
    });
  } catch (error) {
    console.error("[TokenMonitor] aux ingest failed:", error);
  }
}
function installAuxFetchInterceptor() {
  globalThis.__tokenMonitorIngest = handleIngest;
  installClassifierEvents();
  scheduleAutoCardRetry();
  patchWindow(window, true);
  scanIframes();
  if (!observer.instance && typeof MutationObserver === "function" && typeof document !== "undefined") {
    observer.instance = new MutationObserver(() => scanIframes());
    observer.instance.observe(document.documentElement, { childList: true, subtree: true });
  }
}
function uninstallAuxFetchInterceptor() {
  for (const [win, original] of patchedWindows) {
    try {
      win.fetch = original;
      delete win.__tokenMonitorAuxHooked;
    } catch {
    }
  }
  patchedWindows.clear();
  observer.instance?.disconnect();
  observer.instance = null;
  stopAutoCardRetry();
  unregisterAutoCardHooks();
  uninstallClassifierEvents();
  if (globalThis.__tokenMonitorIngest === handleIngest) {
    delete globalThis.__tokenMonitorIngest;
  }
}
function setMarkerConfig({ mode, plotMarkers, fillMarkers } = {}) {
  if (typeof mode === "string") {
    classification.mode = mode;
  }
  if (Array.isArray(plotMarkers)) {
    classification.plotMarkers = plotMarkers.map(String).filter(Boolean);
  }
  if (Array.isArray(fillMarkers)) {
    classification.fillMarkers = fillMarkers.map(String).filter(Boolean);
  }
}
function rescanAuxFrames() {
  scanIframes();
  scheduleAutoCardRetry(true);
}

// src/pricing.js
var DB_NAME = "token_monitor_pricing";
var STORE_NAME = "pricing";
var DB_VERSION = 1;
var CACHE_KEY = "catalogue";
var PRICE_URLS = [
  "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json",
  "https://gcore.jsdelivr.net/gh/BerriAI/litellm@main/model_prices_and_context_window.json",
  "https://cdn.jsdelivr.net/gh/BerriAI/litellm@main/model_prices_and_context_window.json",
  "https://fastly.jsdelivr.net/gh/BerriAI/litellm@main/model_prices_and_context_window.json"
];
var MIN_FUZZY_LENGTH = 6;
var MIN_VALID_ENTRIES = 3;
var SEARCH_RESULT_LIMIT = 40;
var byKey = /* @__PURE__ */ new Map();
var byTail = /* @__PURE__ */ new Map();
var meta = { count: 0, updatedAt: null };
function openDb() {
  return new Promise((resolve, reject) => {
    if (typeof indexedDB === "undefined") {
      reject(new Error("IndexedDB unavailable"));
      return;
    }
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME);
      }
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}
async function idbGet(key) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readonly");
    const request = tx.objectStore(STORE_NAME).get(key);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}
async function idbSet(key, value) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    tx.objectStore(STORE_NAME).put(value, key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}
function isValidPriceData(data) {
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    return false;
  }
  let valid = 0;
  for (const value of Object.values(data)) {
    if (!value || typeof value !== "object") {
      continue;
    }
    if ("input_cost_per_token" in value && "max_tokens" in value) {
      valid += 1;
      if (valid >= MIN_VALID_ENTRIES) {
        return true;
      }
    }
  }
  return false;
}
function setCatalogue(data, updatedAt) {
  byKey = /* @__PURE__ */ new Map();
  byTail = /* @__PURE__ */ new Map();
  for (const [key, value] of Object.entries(data ?? {})) {
    if (!value || typeof value !== "object") {
      continue;
    }
    const inputCost = Number(value.input_cost_per_token);
    const outputCost = Number(value.output_cost_per_token);
    if (!Number.isFinite(inputCost) && !Number.isFinite(outputCost)) {
      continue;
    }
    const cacheReadCost = Number(value.cache_read_input_token_cost ?? value.input_cost_per_token_cache_hit);
    const cacheWriteCost = Number(value.cache_creation_input_token_cost);
    const entry = {
      key,
      inputCost: Number.isFinite(inputCost) ? inputCost : 0,
      outputCost: Number.isFinite(outputCost) ? outputCost : 0,
      cacheReadCost: Number.isFinite(cacheReadCost) ? cacheReadCost : null,
      cacheWriteCost: Number.isFinite(cacheWriteCost) ? cacheWriteCost : null
    };
    const lowerKey = key.toLowerCase();
    byKey.set(lowerKey, entry);
    const tail = lowerKey.split("/").pop();
    if (tail && !byTail.has(tail)) {
      byTail.set(tail, entry);
    }
  }
  meta = { count: byKey.size, updatedAt: updatedAt ?? null };
}
function getPriceMeta() {
  return { ...meta };
}
function searchModels(query, limit = SEARCH_RESULT_LIMIT) {
  const needle = String(query ?? "").trim().toLowerCase();
  if (!byKey.size) {
    return [];
  }
  if (!needle) {
    return [...byKey.keys()].slice(0, limit);
  }
  const matches = [];
  for (const key of byKey.keys()) {
    const index = key.indexOf(needle);
    if (index === -1) {
      continue;
    }
    const tail = key.split("/").pop();
    const isTailHit = tail?.includes(needle) ?? false;
    matches.push({
      key,
      tailHit: isTailHit ? 0 : 1,
      position: index,
      length: key.length
    });
  }
  matches.sort((a, b) => a.tailHit - b.tailHit || a.position - b.position || a.length - b.length || a.key.localeCompare(b.key));
  return matches.slice(0, limit).map((item) => item.key);
}
async function loadCached() {
  try {
    const cached = await idbGet(CACHE_KEY);
    if (cached?.data && isValidPriceData(cached.data)) {
      setCatalogue(cached.data, cached.updatedAt ?? null);
    }
  } catch (error) {
    console.warn("[TokenMonitor] pricing cache load failed:", error);
  }
  return getPriceMeta();
}
async function updatePrices() {
  let lastError = null;
  for (const url of PRICE_URLS) {
    try {
      const response = await fetch(url, { cache: "no-store" });
      if (!response.ok) {
        lastError = new Error(`HTTP ${response.status}`);
        continue;
      }
      const data = await response.json();
      if (!isValidPriceData(data)) {
        lastError = new Error("invalid price data");
        continue;
      }
      const updatedAt = Date.now();
      setCatalogue(data, updatedAt);
      try {
        await idbSet(CACHE_KEY, { data, updatedAt });
      } catch (error) {
        console.warn("[TokenMonitor] pricing cache write failed:", error);
      }
      return { ok: true, ...getPriceMeta(), url };
    } catch (error) {
      lastError = error;
    }
  }
  return { ok: false, error: lastError?.message ?? "unknown error" };
}
function resolvePrice(model) {
  if (!byKey.size || !model) {
    return { found: false };
  }
  const query = String(model).trim().toLowerCase();
  if (!query) {
    return { found: false };
  }
  if (byKey.has(query)) {
    return { found: true, fuzzy: false, ...byKey.get(query) };
  }
  const tail = query.split("/").pop();
  if (tail && byTail.has(tail)) {
    return { found: true, fuzzy: false, ...byTail.get(tail) };
  }
  let best = null;
  for (const [key, entry] of byKey) {
    if (key.length < MIN_FUZZY_LENGTH) {
      continue;
    }
    if (query.includes(key) || key.includes(query)) {
      if (!best || key.length > best.matchLength) {
        best = { ...entry, matchLength: key.length };
      }
    }
  }
  if (best) {
    return { found: true, fuzzy: true, ...best };
  }
  return { found: false };
}
function computeCost({ input, output, cachedInput = 0, cacheWriteInput = 0, model, rate = 1 }) {
  const price = resolvePrice(model);
  if (!price.found) {
    return { found: false, cost: null, usd: null, price };
  }
  const toCount = (value) => {
    const num = Number(value);
    return Number.isFinite(num) && num > 0 ? num : 0;
  };
  const totalInput = toCount(input);
  const totalOutput = toCount(output);
  const cached = toCount(cachedInput);
  const written = toCount(cacheWriteInput);
  const uncachedInput = totalInput >= cached + written ? totalInput - cached - written : totalInput;
  const cacheReadCost = Number.isFinite(price.cacheReadCost) ? price.cacheReadCost : price.inputCost;
  const cacheWriteCost = Number.isFinite(price.cacheWriteCost) ? price.cacheWriteCost : price.inputCost;
  const usd = uncachedInput * price.inputCost + cached * cacheReadCost + written * cacheWriteCost + totalOutput * price.outputCost;
  return { found: true, cost: usd * (Number(rate) || 1), usd, price };
}

// src/combo.js
var MAX_OPTIONS = 40;
var MAX_OPTION_HEIGHT = 220;
var seq2 = 0;
function escapeHtml(value) {
  return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function createList() {
  const list = document.createElement("div");
  list.className = "tm-combo-list tm-hidden";
  list.id = `tm_combo_list_${++seq2}`;
  document.body.appendChild(list);
  return list;
}
function renderOptions(list, options, activeIndex) {
  if (options.length === 0) {
    list.innerHTML = '<div class="tm-combo-empty">价格库中无匹配模型</div>';
    return;
  }
  list.innerHTML = options.map((model, index) => {
    const label = escapeHtml(model);
    const className = index === activeIndex ? "tm-combo-option tm-active" : "tm-combo-option";
    return `<div class="${className}" data-model="${label}">${label}</div>`;
  }).join("");
}
function positionList(input, list) {
  const rect = input.getBoundingClientRect();
  const below = window.innerHeight - rect.bottom;
  const height = Math.min(MAX_OPTION_HEIGHT, list.scrollHeight || MAX_OPTION_HEIGHT);
  list.style.left = `${rect.left}px`;
  list.style.width = `${rect.width}px`;
  list.style.maxHeight = `${height}px`;
  if (below < height && rect.top > below) {
    list.style.top = "auto";
    list.style.bottom = `${window.innerHeight - rect.top}px`;
  } else {
    list.style.bottom = "auto";
    list.style.top = `${rect.bottom + 2}px`;
  }
}
function isInputVisible(input) {
  const rect = input.getBoundingClientRect();
  if (rect.bottom < 0 || rect.top > window.innerHeight || rect.right < 0 || rect.left > window.innerWidth) {
    return false;
  }
  const clipper = input.closest(".tm-settings-body");
  if (clipper) {
    const clip = clipper.getBoundingClientRect();
    if (rect.bottom < clip.top + 2 || rect.top > clip.bottom - 2) {
      return false;
    }
  }
  return true;
}
function attachModelCombo(input, { onCommit } = {}) {
  const list = createList();
  let matches = [];
  let activeIndex = -1;
  let isOpen = false;
  const onWindowChange = () => {
    if (!isOpen) {
      return;
    }
    if (document.activeElement !== input || !isInputVisible(input)) {
      close();
      return;
    }
    positionList(input, list);
  };
  input.setAttribute("autocomplete", "off");
  input.setAttribute("role", "combobox");
  input.setAttribute("aria-expanded", "false");
  input.setAttribute("aria-controls", list.id);
  input.setAttribute("aria-autocomplete", "list");
  function open() {
    list.classList.remove("tm-hidden");
    isOpen = true;
    input.setAttribute("aria-expanded", "true");
    positionList(input, list);
  }
  function close() {
    list.classList.add("tm-hidden");
    isOpen = false;
    input.setAttribute("aria-expanded", "false");
    activeIndex = -1;
  }
  function commit(value) {
    input.value = value;
    close();
    onCommit?.(value.trim());
  }
  function refresh() {
    matches = searchModels(input.value).slice(0, MAX_OPTIONS);
    activeIndex = matches.length ? 0 : -1;
    renderOptions(list, matches, activeIndex);
    open();
  }
  function selectActive() {
    if (activeIndex < 0 || activeIndex >= matches.length) {
      return;
    }
    commit(matches[activeIndex]);
  }
  function move(step) {
    if (matches.length === 0) {
      return;
    }
    activeIndex = (activeIndex + step + matches.length) % matches.length;
    renderOptions(list, matches, activeIndex);
    list.querySelector(".tm-active")?.scrollIntoView({ block: "nearest" });
  }
  input.addEventListener("input", refresh);
  input.addEventListener("focus", refresh);
  input.addEventListener("click", refresh);
  input.addEventListener("keydown", (event) => {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      move(1);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      move(-1);
    } else if (event.key === "Enter") {
      if (!list.classList.contains("tm-hidden")) {
        event.preventDefault();
        event.stopPropagation();
        selectActive();
      }
    } else if (event.key === "Escape") {
      close();
    }
  });
  list.addEventListener("mousedown", (event) => {
    const option = event.target.closest(".tm-combo-option");
    if (!option) {
      return;
    }
    event.preventDefault();
    commit(option.dataset.model);
  });
  input.addEventListener("blur", close);
  window.addEventListener("resize", onWindowChange);
  window.addEventListener("scroll", onWindowChange, true);
  function destroy() {
    close();
    window.removeEventListener("resize", onWindowChange);
    window.removeEventListener("scroll", onWindowChange, true);
    list.remove();
  }
  return { close, refresh, destroy };
}

// src/panel.js
var MODULE_NAME = "token_monitor";
var PANEL_ID = "token_monitor_panel";
var MENU_ID = "token_monitor_menu_entry";
var FAB_ID = "token_monitor_fab";
var MARKER_STORAGE_KEY = "token_monitor_markers";
var AUX_LABELS = { plot: "剧情推进", fill: "填表", other: "其他" };
var KIND_SHORT = { main: "主", plot: "剧情", fill: "填表", other: "其他" };
var CLEAR_PHRASE = "清空";
var defaultSettings = Object.freeze({
  mainGenModel: "",
  plotModel: "",
  fillModel: "",
  rate: 1,
  classifyMode: "auto",
  panelVisible: false,
  panelPosition: null,
  panelSize: null,
  collapsed: false
});
var AUX_MODEL_SETTINGS = { plot: "plotModel", fill: "fillModel", other: "fillModel" };
var bound = false;
var combos = [];
function ctx4() {
  return globalThis.SillyTavern?.getContext();
}
function getSettings() {
  const context = ctx4();
  if (!context?.extensionSettings) {
    return structuredClone(defaultSettings);
  }
  const store = context.extensionSettings;
  if (!store[MODULE_NAME]) {
    store[MODULE_NAME] = structuredClone(defaultSettings);
  }
  for (const key of Object.keys(defaultSettings)) {
    if (!Object.hasOwn(store[MODULE_NAME], key)) {
      store[MODULE_NAME][key] = defaultSettings[key];
    }
  }
  return store[MODULE_NAME];
}
function saveSettings() {
  const context = ctx4();
  if (typeof context?.saveSettingsDebounced === "function") {
    context.saveSettingsDebounced();
  }
}
function loadMarkers() {
  try {
    const parsed = JSON.parse(localStorage.getItem(MARKER_STORAGE_KEY));
    return {
      plotMarkers: Array.isArray(parsed?.plotMarkers) ? parsed.plotMarkers : [],
      fillMarkers: Array.isArray(parsed?.fillMarkers) ? parsed.fillMarkers : []
    };
  } catch {
    return { plotMarkers: [], fillMarkers: [] };
  }
}
function saveMarkers(markers) {
  try {
    localStorage.setItem(MARKER_STORAGE_KEY, JSON.stringify(markers));
  } catch (error) {
    console.warn("[TokenMonitor] cannot save markers:", error);
  }
}
function parseMarkers(text) {
  return String(text ?? "").split(/[\n,]+/).map((item) => item.trim()).filter(Boolean);
}
function detectCurrentModel() {
  const context = ctx4();
  try {
    const model = context?.getChatCompletionModel?.();
    if (typeof model === "string" && model) {
      return model;
    }
  } catch {
  }
  try {
    const model = context?.chatCompletionSettings?.openai_model;
    if (typeof model === "string" && model) {
      return model;
    }
  } catch {
  }
  return "";
}
function formatNumber(value) {
  if (!Number.isFinite(Number(value))) {
    return "—";
  }
  return Math.round(Number(value)).toLocaleString("en-US");
}
function formatCost(value, rate) {
  if (!Number.isFinite(value)) {
    return "—";
  }
  const symbol = Number(rate) === 1 ? "$" : "¥";
  return `${symbol}${value.toFixed(4)}`;
}
function escapeHtml2(value) {
  return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function setText(id, text) {
  const element = document.getElementById(id);
  if (element) {
    element.textContent = text;
  }
}
function configuredModelFor(kind, settings) {
  if (kind === "main") {
    return String(settings.mainGenModel ?? "").trim();
  }
  return String(settings[AUX_MODEL_SETTINGS[kind]] ?? "").trim();
}
function recordCost(entry, rate, settings) {
  const usage = {
    input: entry.input ?? 0,
    output: entry.output ?? 0,
    cachedInput: entry.cachedInput ?? 0,
    cacheWriteInput: entry.cacheWriteInput ?? 0,
    rate
  };
  const candidates = [];
  const configured = configuredModelFor(entry.kind, settings);
  if (configured) {
    candidates.push({ model: configured, source: "configured" });
  }
  if (entry.model && entry.model !== configured) {
    candidates.push({ model: entry.model, source: "captured" });
  }
  const auto = entry.kind === "main" ? detectCurrentModel().trim() : "";
  if (auto && auto !== configured && auto !== entry.model) {
    candidates.push({ model: auto, source: "auto" });
  }
  for (const candidate of candidates) {
    const result = computeCost({ ...usage, model: candidate.model });
    if (result.found) {
      return { found: true, cost: result.cost, source: candidate.source, pricingModel: candidate.model };
    }
  }
  return { found: false, cost: null, source: null, pricingModel: "" };
}
function sumRecordsCost(entries, rate, settings) {
  let cost = 0;
  let anyFound = false;
  let unknown = false;
  let fallback = false;
  let fallbackModel = "";
  for (const entry of entries) {
    const result = recordCost(entry, rate, settings);
    if (result.found) {
      cost += result.cost;
      anyFound = true;
      if (result.source !== "captured") {
        fallback = true;
        fallbackModel = result.pricingModel;
      }
    } else if ((entry.input ?? 0) > 0 || (entry.output ?? 0) > 0) {
      unknown = true;
    }
  }
  return { cost: anyFound ? cost : null, unknown, fallback, fallbackModel };
}
function addMenuEntry() {
  if (document.getElementById(MENU_ID)) {
    return;
  }
  const menu = document.getElementById("extensionsMenu");
  if (menu) {
    const entry = document.createElement("div");
    entry.id = MENU_ID;
    entry.className = "list-group-item flex-container flexGap5";
    entry.innerHTML = '<div class="fa-solid fa-chart-column extensionsMenuExtensionButton"></div>Token 统计';
    entry.addEventListener("click", () => togglePanel());
    menu.appendChild(entry);
    return;
  }
  if (document.getElementById(FAB_ID)) {
    return;
  }
  const fab = document.createElement("div");
  fab.id = FAB_ID;
  fab.className = "fa-solid fa-chart-column";
  fab.title = "Token 统计";
  fab.addEventListener("click", () => togglePanel());
  document.body.appendChild(fab);
}
function buildPanelSkeleton() {
  const panel = document.createElement("div");
  panel.id = PANEL_ID;
  panel.classList.add("tm-hidden");
  panel.innerHTML = `
        <div class="tm-header">
            <span class="tm-title">Token 统计</span>
            <span class="tm-header-actions">
                <span class="tm-icon tm-collapse fa-solid fa-chevron-down" title="折叠/展开"></span>
                <span class="tm-icon tm-close fa-solid fa-xmark" title="隐藏"></span>
            </span>
        </div>
        <div class="tm-body">
            <div class="tm-main">
                <div class="tm-row"><span class="tm-label">主生成 <span class="tm-calls" id="tm-main-calls"></span></span><span class="tm-value" id="tm-main-cost">—</span></div>
                <div class="tm-sub">
                    <span id="tm-main-in">in —</span>
                    <span id="tm-main-out">out —</span>
                    <span id="tm-main-total">total —</span>
                </div>
                <div class="tm-hint" id="tm-main-model"></div>
            </div>
            <div class="tm-aux" id="tm-aux"></div>
            <div class="tm-list">
                <div class="tm-requests-title">请求流水</div>
                <div class="tm-requests" id="tm-requests"></div>
            </div>
            <div class="tm-settings">
                <div class="tm-settings-head" id="tm-settings-toggle">
                    <span>设置</span>
                    <span class="tm-icon fa-solid fa-chevron-down"></span>
                </div>
                <div class="tm-settings-body tm-hidden" id="tm-settings-body">
                    <label class="tm-field">主生成模型
                        <input id="tm-set-model" class="text_pole" type="text" placeholder="留空则自动读取当前模型">
                    </label>
                    <label class="tm-field">剧情推进模型
                        <input id="tm-set-plot-model" class="text_pole" type="text" placeholder="留空则用拦截到的模型名">
                    </label>
                    <label class="tm-field">填表模型（含其他）
                        <input id="tm-set-fill-model" class="text_pole" type="text" placeholder="留空则用拦截到的模型名">
                    </label>
                    <label class="tm-field">汇率（rate=1 时按美元直显）
                        <input id="tm-set-rate" class="text_pole" type="number" min="0" step="0.01">
                    </label>
                    <label class="tm-field">分类模式
                        <select id="tm-set-mode" class="text_pole">
                            <option value="auto">自动（窗口 + 标记）</option>
                            <option value="markers-only">仅标记</option>
                        </select>
                    </label>
                    <label class="tm-field">剧情推进标记（逗号或换行分隔）
                        <textarea id="tm-set-plot-markers" class="text_pole" rows="2"></textarea>
                    </label>
                    <label class="tm-field">填表标记（逗号或换行分隔）
                        <textarea id="tm-set-fill-markers" class="text_pole" rows="2"></textarea>
                    </label>
                    <div class="tm-price-status" id="tm-price-status">未加载价格库</div>
                    <div class="tm-actions">
                        <div id="tm-save-settings" class="menu_button">保存设置</div>
                        <div id="tm-update-prices" class="menu_button">更新价格库</div>
                        <div id="tm-recount" class="menu_button">重新统计</div>
                        <div id="tm-refresh" class="menu_button">刷新</div>
                        <div id="tm-clear" class="menu_button">清空本聊天</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tm-resize tm-resize-bl" title="拖拽调整大小"></div>
        <div class="tm-resize tm-resize-br" title="拖拽调整大小"></div>`;
  return panel;
}
function bindPanelEvents(panel) {
  panel.querySelector(".tm-collapse").addEventListener("click", () => {
    const collapsed = panel.classList.toggle("tm-collapsed");
    const settings = getSettings();
    settings.collapsed = collapsed;
    saveSettings();
  });
  panel.querySelector(".tm-close").addEventListener("click", () => setPanelVisible(false));
  document.getElementById("tm-settings-toggle").addEventListener("click", () => {
    document.getElementById("tm-settings-body").classList.toggle("tm-hidden");
  });
  bindDrag(panel);
  bindResize(panel);
  bindSettingsInputs();
}
function bindDrag(panel) {
  const header = panel.querySelector(".tm-header");
  let dragging = false;
  let startX = 0;
  let startY = 0;
  let originX = 0;
  let originY = 0;
  header.addEventListener("mousedown", (event) => {
    if (event.target.closest(".tm-icon")) {
      return;
    }
    const rect = panel.getBoundingClientRect();
    dragging = true;
    startX = event.clientX;
    startY = event.clientY;
    originX = rect.left;
    originY = rect.top;
    panel.style.right = "auto";
    panel.style.bottom = "auto";
    panel.style.left = `${originX}px`;
    panel.style.top = `${originY}px`;
    event.preventDefault();
  });
  window.addEventListener("mousemove", (event) => {
    if (!dragging) {
      return;
    }
    const nextX = Math.max(0, originX + (event.clientX - startX));
    const nextY = Math.max(0, originY + (event.clientY - startY));
    panel.style.left = `${nextX}px`;
    panel.style.top = `${nextY}px`;
  });
  window.addEventListener("mouseup", () => {
    if (!dragging) {
      return;
    }
    dragging = false;
    const rect = panel.getBoundingClientRect();
    const settings = getSettings();
    settings.panelPosition = { x: Math.round(rect.left), y: Math.round(rect.top) };
    saveSettings();
  });
}
var MIN_PANEL_WIDTH = 320;
var MIN_PANEL_HEIGHT = 220;
function clampSize(value, min, max) {
  return Math.max(min, Math.min(max, value));
}
function bindResize(panel) {
  let resizing = null;
  const startResize = (mode, event) => {
    event.preventDefault();
    event.stopPropagation();
    const rect = panel.getBoundingClientRect();
    panel.style.left = `${rect.left}px`;
    panel.style.top = `${rect.top}px`;
    panel.style.right = "auto";
    panel.style.bottom = "auto";
    resizing = {
      mode,
      startX: event.clientX,
      startY: event.clientY,
      left: rect.left,
      top: rect.top,
      width: rect.width,
      height: rect.height
    };
    panel.classList.add("tm-resized");
  };
  panel.querySelector(".tm-resize-bl")?.addEventListener("mousedown", (event) => startResize("bl", event));
  panel.querySelector(".tm-resize-br")?.addEventListener("mousedown", (event) => startResize("br", event));
  window.addEventListener("mousemove", (event) => {
    if (!resizing) {
      return;
    }
    const dx = event.clientX - resizing.startX;
    const dy = event.clientY - resizing.startY;
    const maxWidth = window.innerWidth - 20;
    const maxHeight = window.innerHeight * 0.95;
    const width = clampSize(
      resizing.mode === "br" ? resizing.width + dx : resizing.width - dx,
      MIN_PANEL_WIDTH,
      maxWidth
    );
    const height = clampSize(resizing.height + dy, MIN_PANEL_HEIGHT, maxHeight);
    panel.style.width = `${Math.round(width)}px`;
    panel.style.height = `${Math.round(height)}px`;
    panel.style.left = `${Math.round(resizing.mode === "bl" ? resizing.left + (resizing.width - width) : resizing.left)}px`;
  });
  window.addEventListener("mouseup", () => {
    if (!resizing) {
      return;
    }
    resizing = null;
    const rect = panel.getBoundingClientRect();
    const settings = getSettings();
    settings.panelSize = { w: Math.round(rect.width), h: Math.round(rect.height) };
    settings.panelPosition = { x: Math.round(rect.left), y: Math.round(rect.top) };
    saveSettings();
  });
}
function bindSettingsInputs() {
  const settings = getSettings();
  const markers = loadMarkers();
  const modelInput = document.getElementById("tm-set-model");
  const plotModelInput = document.getElementById("tm-set-plot-model");
  const fillModelInput = document.getElementById("tm-set-fill-model");
  const rateInput = document.getElementById("tm-set-rate");
  const modeSelect = document.getElementById("tm-set-mode");
  const plotMarkers = document.getElementById("tm-set-plot-markers");
  const fillMarkers = document.getElementById("tm-set-fill-markers");
  modelInput.value = settings.mainGenModel ?? "";
  plotModelInput.value = settings.plotModel ?? "";
  fillModelInput.value = settings.fillModel ?? "";
  rateInput.value = String(settings.rate ?? 1);
  modeSelect.value = settings.classifyMode ?? "auto";
  plotMarkers.value = markers.plotMarkers.join("\n");
  fillMarkers.value = markers.fillMarkers.join("\n");
  combos = [modelInput, plotModelInput, fillModelInput].map((input) => attachModelCombo(input));
  document.getElementById("tm-save-settings").addEventListener("click", handleSaveSettings);
  document.getElementById("tm-update-prices").addEventListener("click", handleUpdatePrices);
  document.getElementById("tm-refresh").addEventListener("click", () => {
    rescanAuxFrames();
    refreshPanel();
  });
  document.getElementById("tm-recount").addEventListener("click", async () => {
    await recomputeChat();
    refreshPanel();
  });
  document.getElementById("tm-clear").addEventListener("click", handleClearChat);
}
async function handleClearChat() {
  const confirmed = await confirmChatClear();
  if (!confirmed) {
    return;
  }
  clearChatTokenData();
  refreshPanel();
}
async function confirmChatClear() {
  const warning = "即将清空当前聊天的<b>全部</b> token 消耗数据（请求流水、楼层统计与汇总），<b>操作无法复原</b>。";
  const context = ctx4();
  const Popup = context?.Popup;
  const POPUP_TYPE = context?.POPUP_TYPE;
  const POPUP_RESULT = context?.POPUP_RESULT;
  if (typeof Popup === "function" && POPUP_TYPE && POPUP_RESULT) {
    try {
      const popup = new Popup(
        `${warning}<br><br>请输入「<b>${CLEAR_PHRASE}</b>」以确认：`,
        POPUP_TYPE.INPUT,
        "",
        {
          okButton: "确认清空",
          cancelButton: "取消",
          placeholder: `输入「${CLEAR_PHRASE}」以确认`,
          onClosing: (instance) => {
            if (instance?.result !== POPUP_RESULT.AFFIRMATIVE) {
              return true;
            }
            if (String(instance?.mainInput?.value ?? "").trim() === CLEAR_PHRASE) {
              return true;
            }
            if (typeof toastr !== "undefined") {
              toastr.warning(`请准确输入「${CLEAR_PHRASE}」后再确认`);
            }
            return false;
          }
        }
      );
      const value = await popup.show();
      return typeof value === "string" && value.trim() === CLEAR_PHRASE;
    } catch (error) {
      console.warn("[TokenMonitor] popup failed, falling back to browser dialog:", error);
    }
  }
  const typed = window.prompt(
    `警告：这会清空当前聊天的全部 token 消耗数据，且无法复原。
请输入「${CLEAR_PHRASE}」以确认：`,
    ""
  );
  return String(typed ?? "").trim() === CLEAR_PHRASE;
}
function applyClassification() {
  const settings = getSettings();
  const markers = loadMarkers();
  setMarkerConfig({
    mode: settings.classifyMode ?? "auto",
    plotMarkers: markers.plotMarkers,
    fillMarkers: markers.fillMarkers
  });
}
function handleSaveSettings() {
  const current = getSettings();
  current.mainGenModel = document.getElementById("tm-set-model").value.trim();
  current.plotModel = document.getElementById("tm-set-plot-model").value.trim();
  current.fillModel = document.getElementById("tm-set-fill-model").value.trim();
  current.rate = Number(document.getElementById("tm-set-rate").value) || 1;
  current.classifyMode = document.getElementById("tm-set-mode").value === "markers-only" ? "markers-only" : "auto";
  saveSettings();
  saveMarkers({
    plotMarkers: parseMarkers(document.getElementById("tm-set-plot-markers").value),
    fillMarkers: parseMarkers(document.getElementById("tm-set-fill-markers").value)
  });
  applyClassification();
  refreshPanel();
  if (typeof toastr !== "undefined") {
    toastr.success("设置已保存，费用已按当前配置重新计算");
  }
}
async function handleUpdatePrices() {
  const button = document.getElementById("tm-update-prices");
  button?.classList.add("disabled");
  try {
    const result = await updatePrices();
    if (result.ok) {
      if (typeof toastr !== "undefined") {
        toastr.success(`价格库已更新（${result.count} 条）`);
      }
    } else if (typeof toastr !== "undefined") {
      toastr.error(`价格库更新失败：${result.error}`);
    }
  } finally {
    button?.classList.remove("disabled");
    updatePriceStatus();
    refreshPanel();
  }
}
function updatePriceStatus() {
  const element = document.getElementById("tm-price-status");
  if (!element) {
    return;
  }
  const meta2 = getPriceMeta();
  if (!meta2.count) {
    element.textContent = "未加载价格库";
    return;
  }
  const time = meta2.updatedAt ? new Date(meta2.updatedAt).toLocaleString() : "未知时间";
  element.textContent = `已加载 ${meta2.count} 条 · ${time}`;
}
function formatRequestTime(ts) {
  const date = new Date(Number(ts) || 0);
  if (Number.isNaN(date.getTime())) {
    return "—";
  }
  return date.toLocaleTimeString([], { hour12: false });
}
function renderRequests() {
  const container = document.getElementById("tm-requests");
  if (!container) {
    return;
  }
  const settings = getSettings();
  const rate = Number(settings.rate) || 1;
  const entries = listRequests();
  if (entries.length === 0) {
    container.innerHTML = '<div class="tm-empty">本聊天暂无请求记录</div>';
    return;
  }
  const regenCounter = /* @__PURE__ */ new Map();
  const rows = entries.map((entry) => {
    const kind = entry.kind in KIND_SHORT ? entry.kind : "other";
    const floorKnown = Number.isInteger(entry.floor);
    let regen = "";
    if (kind === "main" && floorKnown) {
      const seen = (regenCounter.get(entry.floor) ?? 0) + 1;
      regenCounter.set(entry.floor, seen);
      if (seen > 1) {
        regen = `<span class="tm-regen">↻${seen}</span>`;
      }
    }
    const priced = recordCost(entry, rate, settings);
    const costText = priced.found ? `${formatCost(priced.cost, rate)}${priced.source === "captured" ? "" : "*"}` : "—";
    const costTitle = !priced.found ? "未能在价格库中匹配到模型，无法计价" : priced.source === "captured" ? entry.model || "" : `按 ${priced.pricingModel} 计价${entry.model ? `（请求模型：${entry.model}）` : ""}`;
    const floorText = floorKnown ? `${entry.floor}楼` : "未归层";
    const modelText = entry.model || "—";
    return `
            <div class="tm-request" data-floor="${floorKnown ? entry.floor : ""}">
                <span class="tm-request-type"><span class="tm-badge tm-badge-${kind}" title="${AUX_LABELS[kind] ?? "主生成"}">${KIND_SHORT[kind]}</span><span class="tm-request-floor">${floorText}${regen}</span></span>
                <span class="tm-request-out">出 ${entry.output === null ? "—" : formatNumber(entry.output)}</span>
                <span class="tm-request-model" title="${escapeHtml2(modelText)}">${escapeHtml2(modelText)}</span>
                <span class="tm-request-time">${formatRequestTime(entry.ts)}</span>
                <span class="tm-request-in">入 ${entry.input === null ? "—" : formatNumber(entry.input)}</span>
                <span class="tm-request-cost" title="${escapeHtml2(costTitle)}">${costText}</span>
            </div>`;
  });
  container.innerHTML = rows.join("");
  container.querySelectorAll(".tm-request").forEach((row) => {
    const floor = row.getAttribute("data-floor");
    if (floor === "") {
      return;
    }
    row.addEventListener("click", () => {
      const target = document.querySelector(`.mes[mesid="${floor}"]`);
      target?.scrollIntoView({ behavior: "smooth", block: "center" });
    });
  });
}
function renderAux(entries, rate, settings) {
  const container = document.getElementById("tm-aux");
  if (!container) {
    return;
  }
  container.innerHTML = Object.keys(AUX_LABELS).map((category) => {
    const own = entries.filter((entry) => entry.kind === category);
    const input = own.reduce((sum, entry) => sum + (entry.input ?? 0), 0);
    const output = own.reduce((sum, entry) => sum + (entry.output ?? 0), 0);
    const priced = sumRecordsCost(own, rate, settings);
    const costText = priced.cost === null ? "—" : `${formatCost(priced.cost, rate)}${priced.unknown || priced.fallback ? "*" : ""}`;
    const modelNote = priced.fallback ? ` <i>按 ${escapeHtml2(priced.fallbackModel)} 计价</i>` : "";
    return `
            <div class="tm-row tm-aux-row">
                <span class="tm-label">${AUX_LABELS[category]}</span>
                <span class="tm-aux-metrics">${own.length}次 · in ${formatNumber(input)} · out ${formatNumber(output)} · <b>${costText}</b>${modelNote}</span>
            </div>`;
  }).join("");
}
function refreshPanel() {
  const panel = document.getElementById(PANEL_ID);
  if (!panel) {
    return;
  }
  const settings = getSettings();
  const rate = Number(settings.rate) || 1;
  const summary = computeRequestSummary();
  const entries = listRequests();
  const model = settings.mainGenModel || detectCurrentModel();
  const mainEntries = entries.filter((entry) => entry.kind === "main");
  const mainPriced = sumRecordsCost(mainEntries, rate, settings);
  const mainCostText = mainPriced.cost === null ? "—" : `${formatCost(mainPriced.cost, rate)}${mainPriced.unknown || mainPriced.fallback ? "*" : ""}`;
  setText("tm-main-calls", `${summary.main.calls}次`);
  setText("tm-main-in", `in ${formatNumber(summary.main.input)}${summary.main.unknownInput ? "*" : ""}`);
  setText("tm-main-out", `out ${formatNumber(summary.main.output)}`);
  setText("tm-main-total", `total ${formatNumber(summary.main.input + summary.main.output)}`);
  setText("tm-main-cost", mainCostText);
  setText("tm-main-model", model ? `模型：${model}` : "未设置模型（不计算主生成成本）");
  renderAux(entries, rate, settings);
  renderRequests();
  updatePriceStatus();
}
function setPanelVisible(visible, { persist = true } = {}) {
  let panel = document.getElementById(PANEL_ID);
  if (!panel) {
    if (!visible) {
      return;
    }
    panel = buildPanelSkeleton();
    document.body.appendChild(panel);
    applySavedPosition(panel);
    applySavedSize(panel);
    if (getSettings().collapsed) {
      panel.classList.add("tm-collapsed");
    }
    bindPanelEvents(panel);
  }
  panel.classList.toggle("tm-hidden", !visible);
  if (persist) {
    const settings = getSettings();
    settings.panelVisible = Boolean(visible);
    saveSettings();
  }
  if (visible) {
    refreshPanel();
  }
}
function togglePanel() {
  const panel = document.getElementById(PANEL_ID);
  const currentlyVisible = panel ? !panel.classList.contains("tm-hidden") : Boolean(getSettings().panelVisible);
  setPanelVisible(!currentlyVisible);
}
function applySavedPosition(panel) {
  const position = getSettings().panelPosition;
  if (position && Number.isFinite(position.x) && Number.isFinite(position.y)) {
    panel.style.left = `${position.x}px`;
    panel.style.top = `${position.y}px`;
    panel.style.right = "auto";
    panel.style.bottom = "auto";
  }
}
function applySavedSize(panel) {
  const size = getSettings().panelSize;
  if (size && Number.isFinite(size.w) && Number.isFinite(size.h)) {
    panel.style.width = `${clampSize(size.w, MIN_PANEL_WIDTH, window.innerWidth - 20)}px`;
    panel.style.height = `${clampSize(size.h, MIN_PANEL_HEIGHT, window.innerHeight * 0.95)}px`;
    panel.classList.add("tm-resized");
  }
}
function mountPanel() {
  if (bound) {
    return;
  }
  bound = true;
  addMenuEntry();
  applyClassification();
  for (const panel2 of document.querySelectorAll(`#${PANEL_ID}`)) {
    panel2.remove();
  }
  const panel = buildPanelSkeleton();
  document.body.appendChild(panel);
  applySavedPosition(panel);
  applySavedSize(panel);
  if (getSettings().collapsed) {
    panel.classList.add("tm-collapsed");
  }
  bindPanelEvents(panel);
  setPanelVisible(Boolean(getSettings().panelVisible), { persist: false });
}
function unmountPanel() {
  bound = false;
  for (const combo of combos) {
    combo.destroy();
  }
  combos = [];
  document.getElementById(PANEL_ID)?.remove();
  document.getElementById(MENU_ID)?.remove();
  document.getElementById(FAB_ID)?.remove();
}

// src/index.js
var started = false;
var subscriptions = [];
function ctx5() {
  return globalThis.SillyTavern?.getContext();
}
function resolveMessage(data) {
  const chat = ctx5()?.chat ?? [];
  if (Number.isInteger(data) && data >= 0 && data < chat.length) {
    return chat[data];
  }
  return chat.length ? chat[chat.length - 1] : null;
}
function resolveMessageIndex(data) {
  const chat = ctx5()?.chat ?? [];
  if (Number.isInteger(data) && data >= 0 && data < chat.length) {
    return data;
  }
  return chat.length ? chat.length - 1 : null;
}
var pendingMainRequest = null;
var lastMainCapture = null;
function beginMainRequest(generateData) {
  const capture = {
    ts: Date.now(),
    counted: countRequestTokens(generateData),
    usage: null,
    awaitingFetch: true,
    entry: null,
    message: null
  };
  pendingMainRequest = capture;
  lastMainCapture = capture;
}
function takePendingMainRequest() {
  const capture = pendingMainRequest;
  pendingMainRequest = null;
  return capture;
}
function discardPendingMainRequest() {
  pendingMainRequest = null;
}
function claimMainFetch() {
  const capture = pendingMainRequest;
  if (!capture || !capture.awaitingFetch) {
    return false;
  }
  capture.awaitingFetch = false;
  return true;
}
function deliverMainUsage({ usage, model } = {}) {
  const capture = lastMainCapture;
  if (!capture) {
    return;
  }
  const tokens = extractUsageTokens(usage);
  if (!tokens || tokens.input === null && tokens.output === null) {
    return;
  }
  capture.usage = {
    input: tokens.input,
    output: tokens.output,
    cachedInput: tokens.cachedInput,
    cacheWriteInput: tokens.cacheWriteInput,
    model: typeof model === "string" ? model : ""
  };
  if (capture.entry) {
    const fields = {
      cachedInput: tokens.cachedInput,
      cacheWriteInput: tokens.cacheWriteInput
    };
    if (tokens.input !== null) {
      fields.input = tokens.input;
    }
    if (tokens.output !== null) {
      fields.output = tokens.output;
    }
    patchRequest(capture.entry.id, fields);
    if (capture.message) {
      void updateMessageTokens(capture.message, {
        input: tokens.input !== null ? tokens.input : void 0,
        output: tokens.output !== null ? tokens.output : void 0
      });
    }
    refreshPanel();
  }
}
async function onGenerateAfterData(generateData, dryRun) {
  const type = takeGenerationType();
  if (dryRun || isQuietType(type)) {
    return;
  }
  beginMainRequest(generateData);
}
async function finalizeMainRequest({ text, model, message }, index) {
  const capture = takePendingMainRequest();
  if (!capture) {
    return false;
  }
  const countedInput = await capture.counted;
  const usage = capture.usage;
  const input = usage?.input ?? countedInput ?? null;
  const cachedInput = usage?.cachedInput ?? 0;
  const cacheWriteInput = usage?.cacheWriteInput ?? 0;
  let output = usage?.output ?? null;
  if (message) {
    const data = await updateMessageTokens(message, {
      input,
      output: usage?.output
    });
    if (output === null) {
      output = data?.output ?? null;
    }
  } else if (output === null) {
    output = await countTextAsync(text ?? "");
  }
  const entry = appendRequest({
    kind: "main",
    floor: Number.isInteger(index) ? index : null,
    model: model || usage?.model || "",
    input,
    output,
    cachedInput,
    cacheWriteInput,
    ts: capture.ts
  });
  capture.entry = entry ?? null;
  capture.message = message ?? null;
  return true;
}
async function onMessageSent(data) {
  const message = resolveMessage(data);
  if (!message) {
    return;
  }
  await updateMessageTokens(message);
  refreshPanel();
}
async function onMessageReceived(data) {
  const message = resolveMessage(data);
  if (!message) {
    return;
  }
  const finalized = await finalizeMainRequest({
    text: message.mes,
    model: message?.extra?.model || "",
    message
  }, resolveMessageIndex(data));
  if (!finalized) {
    await updateMessageTokens(message);
  }
  refreshPanel();
}
async function onImpersonateReady(text) {
  await finalizeMainRequest({ text, model: "" }, null);
  refreshPanel();
}
async function onMessageEdited(data) {
  const message = resolveMessage(data);
  if (!message) {
    return;
  }
  await updateMessageTokens(message);
  refreshPanel();
}
async function onMessageSwiped(data) {
  const message = resolveMessage(data);
  if (!message) {
    return;
  }
  await updateMessageTokens(message);
  refreshPanel();
}
function onChatChanged() {
  updateChatSummary();
  rescanAuxFrames();
  refreshPanel();
}
function onGenerationStopped() {
  discardPendingMainRequest();
}
function subscribe(eventSource, eventType, handler) {
  if (!eventType || typeof eventSource?.on !== "function") {
    return;
  }
  eventSource.on(eventType, handler);
  subscriptions.push([eventType, handler]);
}
function registerEvents() {
  const context = ctx5();
  const eventSource = context?.eventSource;
  const eventTypes = context?.eventTypes;
  if (!eventSource || !eventTypes || subscriptions.length) {
    return;
  }
  subscribe(eventSource, eventTypes.APP_READY, () => mountPanel());
  subscribe(eventSource, eventTypes.GENERATE_AFTER_DATA, onGenerateAfterData);
  subscribe(eventSource, eventTypes.MESSAGE_SENT, onMessageSent);
  subscribe(eventSource, eventTypes.MESSAGE_RECEIVED, onMessageReceived);
  subscribe(eventSource, eventTypes.IMPERSONATE_READY, onImpersonateReady);
  subscribe(eventSource, eventTypes.MESSAGE_EDITED, onMessageEdited);
  subscribe(eventSource, eventTypes.MESSAGE_SWIPED, onMessageSwiped);
  subscribe(eventSource, eventTypes.MESSAGE_DELETED, onChatChanged);
  subscribe(eventSource, eventTypes.CHAT_CHANGED, onChatChanged);
  subscribe(eventSource, eventTypes.GENERATION_STOPPED, onGenerationStopped);
}
function unregisterEvents() {
  const eventSource = ctx5()?.eventSource;
  for (const [eventType, handler] of subscriptions) {
    eventSource?.removeListener?.(eventType, handler);
  }
  subscriptions = [];
}
function start() {
  if (started) {
    return;
  }
  started = true;
  initTokenTracking();
  globalThis.__tokenMonitorClaimMainFetch = claimMainFetch;
  globalThis.__tokenMonitorDeliverMainUsage = deliverMainUsage;
  installAuxFetchInterceptor();
  void loadCached();
  registerEvents();
}
function stop() {
  if (!started) {
    return;
  }
  started = false;
  unregisterEvents();
  uninstallAuxFetchInterceptor();
  unmountPanel();
  if (globalThis.__tokenMonitorClaimMainFetch === claimMainFetch) {
    delete globalThis.__tokenMonitorClaimMainFetch;
  }
  if (globalThis.__tokenMonitorDeliverMainUsage === deliverMainUsage) {
    delete globalThis.__tokenMonitorDeliverMainUsage;
  }
}
function onEnable() {
  start();
}
function onDisable() {
  stop();
}
function onClean() {
  clearAllTokenData();
  stop();
}
start();
export {
  onClean,
  onDisable,
  onEnable,
  start,
  stop
};
